/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2020  GM Systems Michaˆ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      rRPIC1='@E 999 999 999.99   '
      rRPIC2='@E 999 999 999.99  '
      rRPIC3='@E 999 999 999.99 '
      rRPIC4='@E  999 999.99   '
      rRPIC5='@E  999 999.99  '
      rRPIC6='@E  999 999.99 '
      rRPIC7='@E 999 999.99'
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([ö]+procname())
      mon_drk([ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿])
      mon_drk([³1.Numer Identyfikacji Podatkowej p&_l.atnika ³2.Nr dokumentu             ³3.Status ³])
      mon_drk([³             ]                    +P1+[   ³                           ³         ³])
      mon_drk([ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ])
      mon_drk(rozrzut(NADRUK))
      mon_drk([               I N F O R M A C J A   O   D O C H O D A C H   O R A Z   O   P O B R A N Y C H   Z A L I C Z K A C H])
      mon_drk([                                              N A   P O D A T E K   D O C H O D O W Y])
      mon_drk([                                                 ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿])
      mon_drk([                                        w roku   ³4. Rok                  ³])
      mon_drk([                                                 ³         ]+substr(p4,13)+[       ³])
      mon_drk([ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿])
      mon_drk([³Podstawa prawna:  Art.39 ust.1,art.42 ust.2 pkt1 i art.42e ust.6 ustawy z dnia 26 lipca 1991r. o podatku dochodowym od os&_o.b    ³])
      mon_drk([³                  fizycznych (Dz.U.z 2012r. poz.361 z p&_o.&_x.n.zm.) zwanej dalej "ustaw&_a.";art.35a ust.5 ustawy w brzmieniu         ³])
      mon_drk([³                  obowi&_a.zuj&_a.cym przed dniem 26.10.2007r. 1)                                                                    ³])
      mon_drk([³Sk&_l.adaj&_a.cy:       P&_l.atnik podatku dochodowego od os&_o.b fizycznych.                                                              ³])
      mon_drk([³Termin sk&_l.adania: Do ko&_n.ca lutego roku nast&_e.puj&_a.cego po roku podatkowym-wy&_l.&_a.cznie dla inform.sk&_l.adanych urz&_e.dowi skarb.za pom. ³])
      mon_drk([³                  &_s.rodk&_o.w komun.elektronicznej lub podatnikowi;do ko&_n.ca stycz&_n.ia roku nast&_e.puj&_a.cego po roku podatkowym w przyp.³])
      mon_drk([³                  informacji sk&_l.adanych urz&_e.d.skarb. w formie pisemnej, zgodnie z art.45ba ust.2 ustawy. W przypadku gdy w     ³])
      mon_drk([³                  trakcie roku podat.usta&_l. obowi&_a.zek poboru zal.przez p&_l.atnik&_o.w,o kt&_o.rych mowa w art.39 ust.1 ustawy-term.14dni³])
      mon_drk([³                  od z&_l.oz.pisemnego wniosku przez p&_l.atn.w przyp.zaprzestania dzia&_l.alno&_s.ci przez p&_l.atn.o kt&_o.rych mowa w art.41  ³])
      mon_drk([³                  ust. 1 ustawy, przed ko&_n.cem lutego roku nast&_e.puj&_a.cego po roku podatkowym-do dnia zaprzestania tej dzai&_l.alno&_s.c³])
      mon_drk([³Otrzymuje:        Podatnik oraz urz&_a.d skarbowy 2) wed&_l.ug miejsca zamieszkania podatnika, a w przypadku podatnik&_o.w, o kt&_o.rych   ³])
      mon_drk([³                  mowa w art.3 ust.2a ustawy - urz&_a.d skarbowy w sprawach opodatkowania os&_o.b zagranicznych.                     ³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ A. MIEJSCE SK&__L.ADANIA INFORMACJI                                                                                               ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³5.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest informacja                                                                     ³])
      mon_drk([³  ³ ]+padc(rozrzut(alltrim(P6)),120)+[   ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³6.Cel z&_l.o&_z.enia formularza:                   ]+iif(JAKICEL='I','[XX]','[  ]')+[ 1.z&_l.o&_z.enie informacji           ]+iif(JAKICEL='K','[XX]','[  ]')+[ 2.korekta informacji 3)              ³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ B. DANE IDENTYFIKACYJNE P&__L.ATNIKA   * - dotyczy p&_l.atnika nieb&_e.d&_a.cego osob&_a. fizyczn&_a.  ** - dotyczy p&_l.atnika b&_e.d&_a.cego osob&_a. fizyczn&_a.³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³7.Rodzaj p&_l.atnika  (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                             ³])
      mon_drk([³  ³                                                  ]+iif(spolka_,'[XX]','[  ]')+[  1.P&_l.atnik nieb&_e.d&_a.cy osob&_a. fizyczn&_a.      ]+iif(.not.spolka_,'[XX]','[  ]')+[  2.Osoba fizyczna      ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³8.Nazwa pe&_l.na,REGON*                                                                                                        ³])
      mon_drk([³  ³ ]+iif(spolka_,padc(alltrim(P8),120),space(120))+[   ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³9.Nazwisko, pierwsze imi&_e., data urodzenia**                                                                                 ³])
      mon_drk([³  ³ ]+iif(spolka_,space(120),padc(alltrim(P8),120))+[   ³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ C. DANE IDENTYFIKACYJNE I ADRES ZAMIESZKANIA PODATNIKA                                                                        ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³10.Rodzaj obowi¥zku podatkowego podatnika                                                                                              ³])
      mon_drk('³  ³ [XX] 1. nieograniczony obowi¥zek podatkowy (rezydent)           [  ] 2. ograniczony obowi¥zek podatkowy (nierezydent) 4)   ³')
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³11.]+iif(len(alltrim(P30))=0,'Identyfikator podatkowy NIP','Numer PESEL                ')+[                                                                                              ³])
      mon_drk([³  ³ ]+iif(len(alltrim(P30))=0,padc(alltrim(P29),120),padc(alltrim(P30),120))+[   ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³12.Zagraniczny numer identyfikacyjny podatnika 5)            ] + P_DokIDNr +    [                                           ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³13.Rodzaj numeru identyfikacyjnego (dokumentu stwierdzaj¥cego ³14. Kraj wydania  numeru identyfikacyjnego                   ³])
      mon_drk([³  ³   to¾samo˜†) 6) ] + PadL(PracDokRodzajStr(P_DokIDTyp), 44)+[ ³   (dokumentu stwierdzaj¥cego to¾samo˜†) 6)      ] + P_KrajID + [          ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³15.Nazwisko ]+padc(alltrim(P31),24)+[ ³16.Pierwsze imie ]+padc(alltrim(p32),18)+[ ³17.Data urodz. (dzi-mie-rok) ]+substr(p36,1,4)+[-]+substr(p36,7,4)+[-]+substr(p36,13)+[  ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³18.Kraj    ] + PadC(P_18Kraj, 19) + [ ³19.Wojew&_o.dztwo     ]+P38+[         ³20.Powiat     ]+P38a+[         ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³21.Gmina     ]+P39+[ ³22.Ulica     ]+P40+[ ³23.Nr domu       ]+P41+[    ³24.Nr lokalu       ]+P42+[   ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³25.Miejscowo&_s.&_c. ]+rozrzut(P43)+[  ³26.Kod pocztowy     ]+P44+[     ³27.Poczta    ]+padc(alltrim(p45),20)+[ ³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ D. INFORMACJA O KOSZTACH UZYSKANIA PRZYCHODU Z TYTU&__L.U STOSUNKU S&__L.U&__Z.BOWEGO,STOSUNKU PRACY,SP&__O.&__L.DZIELCZEGO STOSUNKU ORAZ PRACY   ³])
      mon_drk([³    NAK&__L.ADCZEJ                                                                                                                 ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³28.Koszty uzyskania przychod&_o.w, wykazane w poz.26, zosta&_l.y uwzgl&_e.dnione do wysoko&_s.ci przys&_l.uguj&_a.cej podatnikowi (zaznaczy&_c.) ³])
      mon_drk('³  ³   ['+iif(DP28=='1','XX', '  ')+'] 1. z jednego stosun. pracy (stosun.pokrewnych)       ['+iif(DP28=='2','XX', '  ')+'] 2. z wi&_e.cej ni&_z. jednego stosun. pracy (stosun.pokrewnych.)³')
      mon_drk('³  ³   ['+iif(DP28=='3','XX', '  ')+'] 3. z jednego stosun. pracy,(stosun.pokrewnych),      ['+iif(DP28=='4','XX', '  ')+'] 4. z wi&_e.cej ni&_z. jednego stosun. pracy,(stosun.pokrewnych.)³')
      mon_drk([³  ³           podwy&_z.szone w zwi&_a.zku z zamieszkiwaniem podatnika         podwy&_z.szone w zwi&_a.zku z zamieszkiwaniem podatnika poza ³])
      mon_drk([³  ³           poza miejscowo&_s.ci&_a.,w kt&_o.rej znajduje sie zak&_l.ad pracy     miejscowo&_s.ci&_a., w kt&_o.rej znajduje sie zak&_l.ad pracy      ³])
      mon_drk([ÀÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ])
      mon_drk([                                                                                                                 PIT-11 (23) 1/3 ])
      mon_drk([ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿])
      mon_drk([³ E. DOCHODY PODATNIKA, POBRANE ZALICZKI ORAZ POBRANE SK&__L.ADKI 9)                                                                ³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³               &__X.r&_o.d&_l.a przychod&_o.w                                        ³Przychod4)³Koszty uzy³  Dochod  ³Dochod zwo³ Zaliczka ³])
      mon_drk([³                                                                        ³          ³skania prz³          ³lniony od ³ pobrana  ³])
      mon_drk([³                                                                        ³          ³ychodow 8)³   (b-c)  ³podatku 7)³przez plat³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ(a)ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄ(b)ÄÄÄÅÄÄÄÄ(c)ÄÄÄÅÄÄÄÄ(d)ÄÄÄÅÄÄÄÄ(e)ÄÄÄÅÄÄÄÄ(f)ÄÄÄ´])
      mon_drk([³1.Nale&_z.no&_s.ci ze stosunku: pracy,s&_l.u&_z.bowego,sp&_o.&_l.dzielczego i z pracy nak-³29.       ³30.       ³31.       ³32.       ³33.       ³])
      mon_drk([³  &_l.adczej, a tak&_z.e zasi&_l.ki pieni&_e.&_z.ne z ubezpieczenia spolecznego wypla- ³]+tran(p50,rRPIC7)+[³]+tran(p51,rRPIC7)+[³          ³          ³          ³])
      mon_drk([³  cone przez zak&_l.ad pracy,o ktorym mowa w art.31 ustawy,oraz platnikow  ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´]+tran(p53a,rRPIC7)+[³]+tran(zKOR_ZWET,rRPIC7)+[³]+tran(p55,rRPIC7)+[³])
      mon_drk([³  W pozycji 34 nale&_z.y wykaza&_c. przychody,do kt&_o.rych zastosowano odlicze- ³34.       ³35.       ³          ³          ³          ³])
      mon_drk([³  nie koszt&_o.w uzysk.przych.na podst.art.22 ust.9 pkt.3 ustawy           ³          ³          ³          ³          ³          ³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³2.Nale&_z.no&_s.ci z tytu&_l.u cz&_l.onkostwa w rolniczej sp&_o.&_l.dzielni produkcyjnej  ³36.       ³. . . . . ³37.       ³. . . . . ³38.       ³])
      mon_drk([³  lub innej sp&_o.&_l.dzielni zajmuj&_a.cej si&_e. prod.rolna oraz zasilki z Ubez.Sp³]+tran(p61+p50_2,rRPIC7)+[³ . . . . .³]+tran(p61+p50_2,rRPIC7)+[³ . . . . .³]+tran(p63+p53_2,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³3.Emerytury - renty zagraniczne                                         ³39.       ³. . . . . ³40.       ³41.       ³42.       ³])
      mon_drk([³                                                                        ³]+tran(p50_3,rRPIC7)+[³ . . . . .³]+tran(p50_3,rRPIC7)+[³]+tran(zKOR_ZWEM,rRPIC7)+[³]+tran(p53_3,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³4.Nale&_z.nosci za prace przypadajace tymczasowo aresztowanym lub skazanym ³43.       ³. . . . . ³44.       ³. . . . . ³45.       ³])
      mon_drk([³                                                                        ³          ³. . . . . ³          ³. . . . . ³          ³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³5.&__S.wiadczenia wyp&_l.acone z Funduszow: Pracy i Gwarantowanych Swiadczen   ³46.       ³. . . . . ³47.       ³. . . . . ³48.       ³])
      mon_drk([³  Pracowniczych                                                         ³]+tran(p50_4,rRPIC7)+[³ . . . . .³]+tran(p50_4,rRPIC7)+[³ . . . . .³]+tran(p53_4,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³6.Dzialalnosc wykonywana osobiscie,o ktorej mowa w art.13 pkt 2,4,6     ³49.       ³50.       ³51.       ³. . . . . ³52.       ³])
      mon_drk([³  (z wyjatkiem czynnosci z wiersza 7)i 7-9 ustawy,w tym um.zlec i dzielo³]+tran(p50_5,rRPIC7)+[³]+tran(p51_5,rRPIC7)+[³]+tran(p52_5a,rRPIC7)+[³ . . . . .³]+tran(p53_5,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³7. Czynno&_s.ci zwi&_a.zane z pe&_l.nieniem obowi&_a.zk&_o.w spo&_l.ecznych lub obywatel- ³53.       ³54.       ³55.       ³. . . . . ³56.       ³])
      mon_drk([³   skich(art.13 pkt 5 i 6 ustawy).Nalezy wpisac kwote wynikajaca z PIT-R³]+tran(p50_9,rRPIC7)+[³]+tran(p51_9,rRPIC7)+[³]+tran(p52_9a,rRPIC7)+[³ . . . . .³]+tran(p53_9,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³8. Prawa autorskie i inne prawa,o kt&_o.rych mowa w art.18 ustawy          ³57.       ³. . . . . ³58.       ³. . . . . ³59.       ³])
      mon_drk([³                                                                        ³          ³ . . . . .³]+tran(p52_6a,rRPIC7)+[³ . . . . .³]+tran(p53_6,rRPIC7)+[³])
      mon_drk([³ W poz. 60 nale¾y wykaza† przychody, do kt¢rych                         ÃÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´          ³. . . . . ³          ³])
      mon_drk([³ zastosowano koszty uzyskania przychod¢w na                             ³60.       ³61.       ³          ³ . . . . .³          ³])
      mon_drk([³ podstawie art. 22 ust. 9 pkt 1-3 ustawy.                               ³]+tran(p50_6,rRPIC7)+[³]+tran(p51_6,rRPIC7)+[³          ³. . . . . ³          ³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³9. Naleznosci wynikajace z umowy aktywizacyjnej                         ³62.       ³63.       ³64.       ³. . . . . ³65.       ³])
      mon_drk([³                                                                        ³]+tran(p50_1,rRPIC7)+[³]+tran(p51_1,rRPIC7)+[³]+tran(p52_1a,rRPIC7)+[³ . . . . .³]+tran(p53_1,rRPIC7)+[³])
      mon_drk([ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³10.Inne &_x.r&_o.d&_l.a                                                          ³66.       ³. . . . . ³67.       ³68.       ³69.       ³])
      mon_drk([³                                                                        ³]+tran(p50_7,rRPIC7)+[³ . . . . .³]+tran(p50_7,rRPIC7)+[³]+tran(zKOR_ZWIN,rRPIC7)+[³]+tran(p53_7,rRPIC7)+[³])
      mon_drk([ÃÍÍÍÂÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ´])
      mon_drk([³   ³ Sk&_l.adki na ubezpieczenia spo&_l.eczne,o kt&_o.rych mowa w przepisach ustawy,podlegaj&_a.ce odlic³70.               ]+tran(p52+p52z,rRPIC2)+[³])
      mon_drk([³   ÀÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³          ³ w tym zagraniczne, o ktorych mowa w art.26 ust.1 pkt 2a ustawy                  ³71.               ]+tran(zKOR_SPOLZ,rRPIC2)+[³])
      mon_drk([³   ÚÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³   ³ Sk&_l.adki na ubezp.zdrowotne,o kt&_o.rych mowa w przepisach ustawy,podlegaj&_a.ce odliczeniu   ³72.               ]+tran(p54a+p54za+p64,rRPIC2)+[³])
      mon_drk([³   ÀÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³          ³ w tym zagraniczne, o ktorych mowa w art.27b ust.1 pkt 2 ustawy                  ³73.               ]+tran(zKOR_ZDROZ,rRPIC2)+[³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ F. INFORMACJA O PRZYCHODACH ZWOLNIONYCH OD PODATKU ORAZ O ZA&__L.&__A.CZNIKU                                                          ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³Przychody otrzymywane z zagranicy, o kt&_o.rych mowa w art.21 ust.1 pkt 74 ustawy, miedzy   ³74.                               ³])
      mon_drk([³  ³innymi renty inwalidzkie z tytu&_l.u inwalidztwa wojennego                                  ³                                  ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³Przych.pochodz&_a.ce ze &_s.rodk&_o.w bezzwrotnej pomocy zagran.,o kt&_o.rych mowa w art.21ust1pkt46 ³75.                               ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk('³  ³ 76.Do niniejszej informacji do&_l.&_a.czono za&_l.&_a.cznik PIT-R                  [ ]  1. Tak           [ ]  2.Nie                    ³')
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ G. O&__S.WIADCZENIE P&__L.ATNIKA LUB OSOBY ODPOWIEDZIALNEJ ZA OBLICZENIE i POBRANIE PODATKU                                           ³])
      mon_drk([³    O&_s.wiadczam, &_z.e sa mi znane przepisy Kodeksu karnego skarbowego o odpowiedzialno&_s.ci za uchybienie obowi&_a.zkom p&_l.atnika.      ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³ 77.Imi&_e.         ³ 78.Nazwisko          ³ 79.Podpis i piecz&_a.tka                                                             ³])
      mon_drk([³  ³ ]+zDEKLIMIE+[ ³ ]+zDEKLNAZWI+[ ³                                                                                   ³])
      mon_drk([Ã*******************************************************************************************************************************´])
      mon_drk([³ H. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                ³])
      mon_drk([³  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³ 80.Uwagi urz&_e.du skarbowego                                                                                                 ³])
      mon_drk([³  ³                                                                                                                            ³])
      mon_drk([³  ³                                                                                                                            ³])
      mon_drk([³  ³                                                                                                                            ³])
      mon_drk([³  ³                                                                                                                            ³])
      mon_drk([³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´])
      mon_drk([³  ³ 81.Identyfikator przyjmuj&_a.cego formularz                     ³ 82.Podpis przyjmuj&_a.cego formularz                           ³])
      mon_drk([ÀÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ])
      mon_drk([PIT-11 (23) 2/3                                                                                                                  ])
      mon_drk([1)Art.35a ustawy zostal uchylony z dn.26.10.2007r. ustawa z dnia 24.08.2007r. o zmianie ustawy o promocji zatr.i instytuc.rynku  ])
      mon_drk([  pracy oraz o zmianie niektorych innych ustaw (Dz.U.Nr176,poz.1243).Uchylony przepis na mocy art.7 ust.7 powolanej ustawy       ])
      mon_drk([  ma zastosowanie do platnikow do czasu obowiazywania umowy aktywizacyjnej zawartej przed dniem 26.10.2007r.                     ])
      mon_drk([2)Ilekro&_c. jest mowa o urz&_e.dzie skarbowym-oznacza to w&_l.a&_s.ciwy dla podatnika urz&_a.d skarbowy, o kt&_o.rym mowa w przepisach ustawy.    ])
      mon_drk([3)Zgodnie z art.81 ustawy z dnia 29 sierpnia 1997 - Ordynacja podatkowa(Dz.U.z 2012r.poz.749,z p&_o.&_z.n.zm.)zwanej dalej "Ordynacj&_a.  ])
      mon_drk([  podatkow&_a." p&_l.atnik mo&_z.e skorygowa&_c. z&_l.o&_z.on&_a. informacj&_e. przez z&_l.o&_z.enie informacji koryguj&_a.cej wraz z do&_l.aczonym pisemnym         ])
      mon_drk([  uzasadnieniem przyczyn korekty.                                                                                                ])
      mon_drk([4)W przypadku zaznaczenia kwadratu nr 2, w poz. 18-27 nale¾y poda† kraj inny ni¾ Polska oraz adres zamieszkania za granic¥;      ])
      mon_drk([  dodatkowo kod kraju wydania dokumentu powinien by† zgodny z krajem adresu zamieszkania.                                        ])
      mon_drk([5)W poz. 12 nale¾y poda† numer sˆu¾¥cy identyfikacji dla cel¢w podatkowych lub ubezpieczeä spoˆecznych uzyskany w paästwie,      ])
      mon_drk([  w kt¢rym podatnik ma miejsce zamieszkania. W przypadku braku takiego numeru w poz. 12 nale¾y poda† numer dokumentu             ])
      mon_drk([  stwierdzaj¥cego to¾samo˜† podatnika, uzyskanego w tym paästwie.                                                                ])
      mon_drk([6)Poz. 13 i 14 wypeˆnia pˆatnik, kt¢ry w poz. 12 podaˆ zagraniczny numer identyfikacyjny podatnika.                              ])
      mon_drk([7)W kwocie przychodow,w czesci E,nie uwzglednia sie przychodow wolnych od podatku na podstawie przepisow ustawy oraz przychodow, ])
      mon_drk([  od ktorych na podstawie przepisow Ordynacji podatkowej zaniechano poboru podatku;jednakze w kolumnie e nalezy wykazac          ])
      mon_drk([  dochody zwolnione od podatku na podstawie umow o unikaniu podwojnego opodatkowania lub innych umow miedzynarodowych.           ])
      mon_drk([8)W kwocie kosztow uzyskania przychodow wykazuje sie koszty faktycznie uwzglednione przez platnika przy poborze zalicz.na podatek])
      mon_drk([9)W poz.66-69 nie wykazuje sie skladek,ktorych podstawe wymiaru stanowi doch(przych)wolny od podatku na podst.ustawy oraz skladek])
      mon_drk([  ktorych podstawe wymiaru stanowi dochod,od ktorego na podstawie przep.Ordynacji podat.zaniechano poboru podatku,a w przypadku  ])
      mon_drk([  skladek zagranicznych,ktorych podstawe wymiaru stanowi doch(przych) zwolniony od podatku na podstawie umow o unikaniu          ])
      mon_drk([  podwojnego opodatkowania.                                                                                                      ])
      mon_drk([                                                            POUCZENIE                                                            ])
      mon_drk([Za uchybienie obowiazkom platnika grozi odpowiedzialnosc przewidziana w Kodeksie karnym skarbowym.                               ])
      mon_drk([                                                                                                                 PIT-11 (23) 3/3 ])
      mon_drk([ş])
end
