/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2019  GM Systems Micha┬ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      rRPIC1='@E 999 999   '
      rRPIC2='@E 99 999.99'
      rRPIC3='@E 9 999.99'
      rRPIC4='@E     999   '
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([Ж]+procname())
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддбддддддддд©])
      mon_drk([Ё1.Identyfikator podatkowy NIP p&_l.atnika    Ё2.Nr dokumentu             Ё3.Status Ё])
      mon_drk([Ё             ]                    +rozrzut(P1)+[   Ё                           Ё         Ё])
      mon_drk([юддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддаддддддддды])
      mon_drk([])
      mon_drk([P I T - 8 A R])
      mon_drk([            DEKLARACJA  ROCZNA  O  ZRYCZA&__L.TOWANYM  PODATKU  DOCHODOWYM ])
      mon_drk([                                 здддддддддддддддддд©])
      mon_drk([                                 Ё4.Rok             Ё])
      mon_drk([                              ZA Ё       ]+p4+[   Ё])
      mon_drk([                                 юдддддддддддддддддды])
      mon_drk([])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([ЁPodstawa prawna:   Art.42 ust.1a ustawy z dnia 26.07.1991r.o podatku dochodowym od os&_o.b fizycznych (Dz.U.z 2012r. poz.361,     Ё])
      mon_drk([Ё                   z p&_o.&_x.n.zm.) zwanej dalej "ustaw&_a.".                                                                          Ё])
      mon_drk([ЁSk&_l.adaj&_a.cy:        P&_l.atnik zrycza&_l.towanego podatku dochodowego od os&_o.b fizycznych.                                             Ё])
      mon_drk([ЁTerminy sk&_l.adania: Do ko&_n.ca stycznia roku nast&_e.puj&_a.cego po roku podatkowym. W przypadku zaprzestania dzia&_l.alno&_s.ci przez        Ё])
      mon_drk([Ё                   p&_l.atnika przed tym terminem - do dnia zaprzestania tej dzia&_l.alno&_s.ci.                                        Ё])
      mon_drk([ЁMiejsce sk&_l.adania: Urz&_a.d skarbowy 1) wed&_l.ug miejsca zamieszkania p&_l.atnika, a je&_z.eli p&_l.atnik nie jest osob&_a. fizyczn&_a., wed&_l.ug    Ё])
      mon_drk([Ё                   siedziby b&_a.d&_x. miejsca prowadzenia dzia&_l.alno&_s.ci, gdy p&_l.atnik nie posiada siedziby 2).                        Ё])
      mon_drk([ц*******************************************************************************************************************************Ё])
      mon_drk([Ё A. MIEJSCE I CEL SK&__L.ADANIA DEKLARACJI                                                                                         Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё5.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest deklaracja                                                                     Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P6)),120)+[   Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё6.Cel z&_l.o&_z.enia formularza  (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                     Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk('Ё  Ё                            '+iif(zDEKLKOR="D","[XX]","[  ]")+'  1.zlozenie deklaracji                    '+iif(zDEKLKOR<>"D","[XX]","[  ]")+'  2.korekta deklaracji 3)                    Ё')
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё B. DANE IDENTYFIKACYJNE P&__L.ATNIKA                                                                                              Ё])
      mon_drk([Ё    * - dotyczy p&_l.atnika nieb&_e.d&_a.cego osob&_a. fizyczn&_a.                    ** - dotyczy p&_l.atnika b&_e.d&_a.cego osob&_a. fizyczn&_a.           Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё7.Rodzaj p&_l.atnika  (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                             Ё])
      mon_drk([Ё  Ё                           ]+iif(spolka_,'[XX]','[  ]')+[  1.P&_l.atnik nie b&_e.d&_a.cy osob&_a. fizyczn&_a.          ]+iif(.not.spolka_,'[XX]','[  ]')+[  2.Osoba fizyczna                        Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё8.Nazwa pe&_l.na, REGON*   /   Nazwisko, pierwsze imi&_e., data urodzenia, **                                                     Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P8)),120)+[   Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё C. WYKAZ NALE&__Z.NEGO ZRYCZA&__L.TOWANEGO PODATKU DOCHODOWEGO POBRANEGO ZA POSZCZEG&__O.LNE MIESI&__A.CE ROKU PODATKOWEGO                    Ё])
      mon_drk([цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё 1.Wygrane w konkursach, grach i zak&_l.adach wzajemnych oraz nagrody zwi&_a.zane ze sprzeda&_z.&_a. premiow&_a. (art.30 ust.1 pkt 2 ustawy)  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё 9.           Ё10.           Ё11.           Ё12.           Ё13.           Ё14.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё15.           Ё16.           Ё17.           Ё18.           Ё19.           Ё20.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 2.&__S.wiadczenia otrzymane przez emeryt&_o.w lub rencist&_o.w b&_e.d&_a.cych by&_l.ymi pracownikami (art.30 ust.1 pkt 4 ustawy)                 Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё21.           Ё22.           Ё23.           Ё24.           Ё25.           Ё26.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё27.           Ё28.           Ё29.           Ё30.           Ё31.           Ё32.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 3.&__S.wiadczenia pieni&_e.&_z.ne otrzymane przez funkcjonariuszy s&_l.u&_z.b mundurowych oraz &_z.o&_l.nierzy,wymienione w art.30 ust1 pkt4a ustawyЁ])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё33.           Ё34.           Ё35.           Ё36.           Ё37.           Ё38.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё39.           Ё40.           Ё41.           Ё42.           Ё43.           Ё44.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([                                                                                                                  PIT-8AR (6) 1/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё 4.Jednorazowe odszkodowania za skr&_o.cenie okresu wypowiedzenia wyp&_l.acane &_z.o&_l.nierzom zwalnianym z zawodowej s&_l.u&_z.by wojskowej    Ё])
      mon_drk([Ё   (art.30 ust.1 pkt 13 ustawy)                                                                                                Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё45.           Ё46.           Ё47.           Ё48.           Ё49.           Ё50.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё51.           Ё52.           Ё53.           Ё54.           Ё55.           Ё56.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 5.Kwota wyp┬at z indywidualnego konta zabezpieczenia emerytalnego (art. 30 ust. 1 pkt 14 ustawy)                              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё57.           Ё58.           Ё59.           Ё60.           Ё61.           Ё62.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё63.           Ё64.           Ё65.           Ё66.           Ё67.           Ё68.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 6. Nale╬no≤ci os╒b zagranicznych, wymienione w art. 29 ustawy                                                                 Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё69.           Ё70.           Ё71.           Ё72.           Ё73.           Ё74.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё  ]+tran(z601,rRPIC1)+[  Ё  ]+tran(z602,rRPIC1)+[  Ё  ]+tran(z603,rRPIC1)+[  Ё  ]+tran(z604,rRPIC1)+[  Ё  ]+tran(z605,rRPIC1)+[  Ё  ]+tran(z606,rRPIC1)+[  Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё75.           Ё76.           Ё77.           Ё78.           Ё79.           Ё80.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z607,rRPIC1)+[  Ё  ]+tran(z608,rRPIC1)+[  Ё  ]+tran(z609,rRPIC1)+[  Ё  ]+tran(z610,rRPIC1)+[  Ё  ]+tran(z611,rRPIC1)+[  Ё  ]+tran(z612,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 7.Odsetki od po╬yczek (z wyj╔tkiem gdy udzielanie po╬yczek jest przedmiotem dzia┬alno≤ci gospodarczej), odsetki               Ё])
      mon_drk([Ё   i dyskonto od papier╒w warto≤ciowych (art. 30a ust. 1 pkt 1 i 2 ustawy)                                                     Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё81.           Ё82.           Ё83.           Ё84.           Ё85.           Ё86.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё87.           Ё88.           Ё89.           Ё90.           Ё91.           Ё92.           Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 8.Odsetki lub inne przychody od ≤rodk╒w pieni╘╬nych zgromadzonych na rachunku podatnika lub w innych formach                  Ё])
      mon_drk([Ё   oszcz╘dzania, przechowywania lub inwestowania (art. 30a ust. 1 pkt 3 ustawy)                                                Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё93.           Ё94.           Ё95.           Ё96.           Ё97.           Ё98.           Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё99.           Ё100.          Ё101.          Ё102.          Ё103.          Ё104.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 9.Dywidendy i inne przychody z tytu┬u udzia┬u w zyskach os╒b prawnych (art. 30a ust. 1 pkt 4 ustawy)                          Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё105.          Ё106.          Ё107.          Ё108.          Ё109.          Ё110.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё111.          Ё112.          Ё113.          Ё114.          Ё115.          Ё116.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([])
      mon_drk([])
      mon_drk([PIT-8AR (6) 2/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё10.Doch╒d z tytu┬u udzia┬u w funduszach kapita┬owych (art. 30a ust. 1 pkt 5 ustawy)                                            Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё117.          Ё118.          Ё119.          Ё120.          Ё121.          Ё122.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё123.          Ё124.          Ё125.          Ё126.          Ё127.          Ё128.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё11.Kwoty wyp┬acane po ≤mierci cz┬onka otwartego funduszu emerytalnego (art. 30a ust. 1 pkt 6 ustawy)                           Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё129.          Ё130.          Ё131.          Ё132.          Ё133.          Ё134.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё135.          Ё136.          Ё137.          Ё138.          Ё139.          Ё140.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё12.Dochody cz┬onka pracowniczego funduszu emerytalnego z tytu┬u przeniesienia akcji (art. 30a ust. 1 pkt 7 ustawy)             Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё141.          Ё142.          Ё143.          Ё144.          Ё145.          Ё146.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё147.          Ё148.          Ё149.          Ё150.          Ё151.          Ё152.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё13.Przychody z tytu┬u zbycia prawa poboru akcji (art. 30a ust. 1 pkt 8 ustawy)                                                 Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё153.          Ё154.          Ё155.          Ё156.          Ё157.          Ё158.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё159.          Ё160.          Ё161.          Ё162.          Ё163.          Ё164.          Ё])
      mon_drk([Ё                                     Ё              Ё              Ё              Ё              Ё              Ё              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё14. Inne nale╬no≤ci niewymienione w wierszach 1-13                                                                             Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё165.          Ё166.          Ё167.          Ё168.          Ё169.          Ё170.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё  ]+tran(z201,rRPIC1)+[  Ё  ]+tran(z202,rRPIC1)+[  Ё  ]+tran(z203,rRPIC1)+[  Ё  ]+tran(z204,rRPIC1)+[  Ё  ]+tran(z205,rRPIC1)+[  Ё  ]+tran(z206,rRPIC1)+[  Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё171.          Ё172.          Ё173.          Ё174.          Ё175.          Ё176.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z207,rRPIC1)+[  Ё  ]+tran(z208,rRPIC1)+[  Ё  ]+tran(z209,rRPIC1)+[  Ё  ]+tran(z210,rRPIC1)+[  Ё  ]+tran(z211,rRPIC1)+[  Ё  ]+tran(z212,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё15.Suma pobranego zrycza┬towanego podatku do przekazania do urz╘du skarbowego za poszczeg╒lne miesi╔ce z wierszy 1-14          Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё177.          Ё178.          Ё179.          Ё180.          Ё181.          Ё182.          Ё])
      mon_drk([Ё  Kwoty pobranego                    Ё  ]+tran(z301,rRPIC1)+[  Ё  ]+tran(z302,rRPIC1)+[  Ё  ]+tran(z303,rRPIC1)+[  Ё  ]+tran(z304,rRPIC1)+[  Ё  ]+tran(z305,rRPIC1)+[  Ё  ]+tran(z306,rRPIC1)+[  Ё])
      mon_drk([Ё  zrycza&_l.towanego podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё183.          Ё184.          Ё185.          Ё186.          Ё187.          Ё188.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z307,rRPIC1)+[  Ё  ]+tran(z308,rRPIC1)+[  Ё  ]+tran(z309,rRPIC1)+[  Ё  ]+tran(z310,rRPIC1)+[  Ё  ]+tran(z311,rRPIC1)+[  Ё  ]+tran(z312,rRPIC1)+[  Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([                                                                                                                  PIT-8AR (6) 3/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё16.Wynagrodzenie z tytu┬u terminowego wp┬acania podatku dochodowego za poszczeg╒lne miesi╔ce - zgodnie z art. 28               Ё])
      mon_drk([Ё   Ordynacji podatkowej                                                                                                        Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё189.          Ё190.          Ё191.          Ё192.          Ё193.          Ё194.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z401,rRPIC1)+[  Ё  ]+tran(z402,rRPIC1)+[  Ё  ]+tran(z403,rRPIC1)+[  Ё  ]+tran(z404,rRPIC1)+[  Ё  ]+tran(z405,rRPIC1)+[  Ё  ]+tran(z406,rRPIC1)+[  Ё])
      mon_drk([Ё          Kwoty wynagrodzenia        цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё195.          Ё196.          Ё197.          Ё198.          Ё199.          Ё200.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z407,rRPIC1)+[  Ё  ]+tran(z408,rRPIC1)+[  Ё  ]+tran(z409,rRPIC1)+[  Ё  ]+tran(z410,rRPIC1)+[  Ё  ]+tran(z411,rRPIC1)+[  Ё  ]+tran(z412,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё17.Kwoty do wp┬aty za poszczeg╒lne miesi╔ce roku podatkowego                                                                   Ё])
      mon_drk([Ё   oszcz╘dzania, przechowywania lub inwestowania (art. 30a ust. 1 pkt 3 ustawy)                                                Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё201.          Ё202.          Ё203.          Ё204.          Ё205.          Ё206.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z501,rRPIC1)+[  Ё  ]+tran(z502,rRPIC1)+[  Ё  ]+tran(z503,rRPIC1)+[  Ё  ]+tran(z504,rRPIC1)+[  Ё  ]+tran(z505,rRPIC1)+[  Ё  ]+tran(z506,rRPIC1)+[  Ё])
      mon_drk([Ё           Kwoty do wp&_l.aty *)        цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё207.          Ё208.          Ё209.          Ё210.          Ё211.          Ё212.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z507,rRPIC1)+[  Ё  ]+tran(z508,rRPIC1)+[  Ё  ]+tran(z509,rRPIC1)+[  Ё  ]+tran(z510,rRPIC1)+[  Ё  ]+tran(z511,rRPIC1)+[  Ё  ]+tran(z512,rRPIC1)+[  Ё])
      mon_drk([ц*******************************************************************************************************************************Ё])
      mon_drk([Ё D. PODPIS P&__L.ATNIKA LUB OSOBY WYZNACZONEJ DO OBLICZENIA I POBRANIA PODATKU / PELNOMOCNIKA PLATNIKA                             Ё])
      mon_drk([Ё    O&_s.wiadczam, &_z.e s&_a. mi znane przepisy Kodeksu karnego skarbowego o odpowiedzialno&_s.ci za uchybienie obowi&_a.zkom p&_l.atnika       Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё213.Imi&_e.                               Ё214.Nazwisko                           Ё215.Podpis i piecz&_a.tka                      Ё])
      mon_drk([Ё  Ё                                       Ё                                       Ё                                            Ё])
      mon_drk([Ё  Ё                                       Ё                                       Ё                                            Ё])
      mon_drk([Ё  Ё            ]+zDEKLIMIE+[            Ё          ]+zDEKLNAZWI+[         Ё                                            Ё])
      mon_drk([Ё  Ё                                       Ё                                       Ё                                            Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё E. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё216.Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё205.Identyfikator przyjmuj&_a.cego formularz                     Ё206.Podpis przyjmuj&_a.cego formularz                           Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([1) Ilekro&_c. w deklaracji jest mowa o urz&_e.dzie skarbowym-oznacza to w&_l.a&_s.ciwy dla p&_l.atnika urz&_a.d skarbowy, o kt&_o.rym mowa            ])
      mon_drk([   w przepisach ustawy.])
      mon_drk([])
      mon_drk([2) Deklaracj&_e. dotycz&_a.c&_a. podatku pobranego zgodnie z art.30a ust.2a ustawy, p&_l.atnicy, o kt&_o.rych mowa w art.41 ust.10 ustawy,  ])
      mon_drk([   przesy&_l.aj&_a. do urz&_e.du skarbowego w&_l.a&_s.ciwego w sprawach opodatkowania os&_o.b zagranicznych.  ])
      mon_drk([])
      mon_drk([3) Zgodnie z art.81 Ordynacji podatkowej,p&_l.atnik mo&_z.e skorygowa&_c. z&_l.o&_z.on&_a. deklaracj&_e. poprzez z&_l.o&_z.enie deklaracji koryguj&_a.cej wraz ])
      mon_drk([   z do&_l.&_a.czonym pisemnym uzasadnieniem przyczyn korekty.                                                                         ])
      mon_drk([])
      mon_drk([                                                           *) Pouczenie])
      mon_drk([])
      mon_drk([   W przypadku niewp&_l.acenia w obowi&_a.zuj&_a.cym terminie kwoty z poz.od 189 do 200 lub wp&_l.acenia ich w niepe&_l.nej wysoko&_s.ci, niniejsza])
      mon_drk([   deklaracja stanowi podstaw&_e. do wystawienia tytu&_l.u wykonawczego, zgodnie z przepisami ustawy z dnia 17.06.1966r. o post&_e.powaniu])
      mon_drk([   egzekucyjnym w administracji (Dz.U.z 2012r. poz.1015,z p&_o.&_x.n.zm.)])
      mon_drk([])
      mon_drk([   Za uchybienie obowi&_a.zkom p&_l.atnika grozi odpowiedzialno&_s.&_c. przewidziana w Kodeksie karnym skarbowym.  ])
      mon_drk([])
      mon_drk([                                                          Obja&_s.nienia])
      mon_drk([])
      mon_drk([1. Deklaracje wype&_l.niaj&_a. p&_l.atnicy okre&_s.leni w art.41 ustawy,je&_z.eli s&_a. obowi&_a.zani pobiera&_c. zrycza&_l.towany podatek dochodowy od     ])
      mon_drk([   dokonywanych wyp&_l.at (&_s.wiadcze&_n.) lub stawianych do dyspozycji podatnika lub posiadacza rachunku zbiorczego, pieni&_e.dzy lub])
      mon_drk([   warto&_s.ci pieni&_e.&_z.nych, oraz sp&_o.&_l.dzielnie pobieraj&_a.ce zrycza&_l.towany podatek dochodowy stosownie do postanowien art.18 ustawy])
      mon_drk([   z dnia 12 listopada 2003r. o zmianie ustawy o podatku dochodowym od os&_o.b fizycznych oraz niekt&_o.rych innych ustaw (Dz.U.Nr 202,])
      mon_drk([   poz.1956,z p&_o.&_x.n.zm.).])
      mon_drk([])
      mon_drk([2. Kwoty zrycza&_l.towanego podatku wykazywanego w wierszach 5-9 i 13 nale&_z.y oblicza&_c. z uwzgl&_e.dnieniem postanowie&_n. um&_o.w o unikaniu  ])
      mon_drk([   podw&_o.jnego opodatkowania.      ])
      mon_drk([])
      mon_drk([3. Kwoty podatku i wynagrodzenia przys&_l.uguj&_a.cego p&_l.atnikom z tytu&_l.u terminowego wp&_l.acenia podatku dochodowego zaokr&_a.gla si&_e.,])
      mon_drk([   zgodnie z art.63 Ordynacji podatkowej])
      mon_drk([])
      mon_drk([4. Ilekro&_c. w deklaracji jest mowa o Ordynacji podatkowej-oznacza to ustaw&_e. z dnia 29.08.1997r.-Ordynacja podatkowa (Dz.U.z 2012r.])
      mon_drk([   poz.749,z p&_o.&_x.n.zm.)                                                                                                       ])
      mon_drk([])
      mon_drk([])
      mon_drk([PIT-8AR (6) 4/4])
      mon_drk([Ч])
end


