/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2019  GM Systems Micha┬ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([Ж]+procname())
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддбддддддддд©])
      mon_drk([Ё1.Numer Identyfikacji Podatkowej          Ё2.Nr dokumentu             Ё3.Status Ё])
      mon_drk([Ё             ]+substr(P3,1,7)+[-]+substr(P3,8,7)+[-]+substr(P3,15,5)+[-]+substr(P3,20)+[   Ё                           Ё         Ё])
      mon_drk([юддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддаддддддддды])
      mon_drk([P I T - 5 L])
      mon_drk([])
      mon_drk([    D E K L A R A C J A   N A   Z A L I C Z K &__E.   M I E S I &__E. C Z N &__A.])
      mon_drk([ N A   P O D A T E K   D O C H O D O W Y   W E D &__L. U G   S T A W K I   1 9 %])
      mon_drk([                       здддддддддддддддддд©])
      mon_drk([                  Z A  Ё4.Miesi&_a.c-rok     Ё])
      mon_drk([                       Ё   ]+substr(p4,1,5)+[-]+substr(p4,7)+[ Ё])
      mon_drk([                       юдддддддддддддддддды])
      mon_drk([ Formularz jest przeznaczony dla podatnik&_o.w prowadz&_a.cych pozarolnicz&_a. dzia&_l.alno&_s.&_c. gospodarcz&_a., opodatkowan&_a. na zasadach ])
      mon_drk([ okre&_s.lonych w art.30c ustawy z dnia 26.07.1991r. o podatku dochodowym od os&_o.b fizycznych (Dz.U.z 2000r. Nr14,poz.176,z p&_o.&_x.n.zm.)])
      mon_drk([ zwanej dalej "ustaw&_a.".])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([ЁPodstawa prawna  :Art.44 ust.6 ustawy.                                                                                         Ё])
      mon_drk([ЁSk&_l.adaj&_a.cy       :Podatnik podatku dochodowego od os&_o.b fizycznych.                                                             Ё])
      mon_drk([ЁTermin sk&_l.adania :Za miesi&_a.ce od stycznia do listopada - do dnia 20 ka&_z.dego miesi&_a.ca za miesi&_a.c poprzedni (zaliczke za grudzie&_n.Ё])
      mon_drk([Ё                  w wysoko&_s.ci nale&_z.nej za listopad uiszcza si&_e. w terminie do 20 grudnia, bez sk&_l.adania deklaracji).            Ё])
      mon_drk([ЁMiejsce sk&_l.adania:Urz&_a.d skarbowy 1) wg miejsca zamieszkania lub pobytu podatnika w ostatnim dniu okresu rozliczeniowego,kt&_o.regoЁ])
      mon_drk([Ё                  dotyczy deklaracja.                                                                                          Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё A. MIEJSCE SK&__L.ADANIA DEKLARACJI                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё5.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest deklaracja                                                                     Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P5)),120)+[   Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё B. DANE PODATNIKA                                                                                                             Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё B.1. DANE IDENTYFIKACYJNE                                                                                                     Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё6.Nazwisko      ]+padc(rozrzut(alltrim(p7)),60)+space(48)+[Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё7.Pierwsze imie  ]+padc(rozrzut(alltrim(p8)),40)+[     Ё8.Data urodz.(dzien-miesiac-rok) ]+substr(p12,1,5)+[-]+substr(p12,6,5)+[-]+substr(p12,11)+space(8)+[Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё B.2. ADRES ZAMIESZKANIA                                                                                                       Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 9.Kraj         P O L S K A     Ё 10.Wojew&_o.dz. ]+padc(alltrim(P15),35)+[ Ё11.Powiat]+padc(alltrim(P15a),30)+[ Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддаддддбдддддддддддддддддддддддддддддддддддддддбдддддадддддддддддддддддбдддддддддддддддддддддд╢])
      mon_drk([Ё  Ё12.Gmina]+padc(alltrim(P16),29)+[Ё13.Ulica ]+padc(rozrzut(alltrim(p17)),30)+[Ё14.Nr domu  ]+padc(alltrim(P18),10)+[ Ё15.Nr lokal.]+padc(alltrim(P19),10)+[Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддадддддддддддддддддддбдддддддддддддддддддаддддбддддддддддддддддддадддддддддддддддддддддд╢])
      mon_drk([Ё  Ё16.Miejscowo&_s.&_c.  ]+padc(rozrzut(alltrim(p20)),40)+[ Ё17.Kod pocztowy  ]+P21+[ Ё18.Poczta  ]+padc(alltrim(p22),25)+[     Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё C. USTALENIE DOCHODU/STRATY                                                                                                   Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддбдддддддддддддддддддддбдддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё          &__X.r&_o.d&_l.o przychod&_o.w            Ё      Przych&_o.d 2)    ЁKoszty uzysk.przycho.Ё    Doch&_o.d (b-c)     Ё    Strata (c-b)     Ё])
      mon_drk([Ё                  a                    Ё          b          Ё          c          Ё          d          Ё          e          Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё1.Pozarolnicza dzia&_l.alno&_s.&_c. gospodarcza Ё19.                  Ё20.                  Ё21.                  Ё22.                  Ё])
      mon_drk([Ё                                       Ё  ]+tran(p27,dRPICe)+[     Ё  ]+tran(p28,dRPICe)+[     Ё    ]+tran(p29,dRPIC)+[     Ё    ]+tran(p30,dRPIC)+[     Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё D. ODLICZENIE STRAT I SK&__L.ADEK NA UBEZPIECZENIE SPO&__L.ECZNE                                                                      Ё])
      mon_drk([Ё    Suma kwot z cz&_e.&_s.ci D nie mo&_z.e przekroczy&_c. kwoty z poz.21                                                                   Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё Straty z lat ubieg&_l.ych zgodnie z art.9 ust.3 i 3a ustawy z uwzgl&_e.dnieniem art.3ustawy z dn.11.08.2001Ё23.                  Ё])
      mon_drk([Ё  Ё o szczeg&_o.lnych rozwi&_a.zaniach prawnych zwi&_a.zanych z usuwaniem skutk&_o.w powodzi z lipca i sierpnia 2001rЁ                     Ё])
      mon_drk([Ё  Ё oraz o zmianie niekt&_o.rych ustaw (Dz.U.Nr 84, poz.907, z p&_o.&_x.niejszymi zmianami)                       Ё      ]+tran(P51,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё Sk&_l.adki na ubezpieczenie spo&_l.eczne-na podstawie art.30c ust.2 w zwi&_a.zku z art.26 ust.1 pkt2 lit.a,   Ё24.                  Ё])
      mon_drk([Ё  Ё z zastrze&_z.eniem art.30c ust.3 ustawy 3)                                                              Ё      ]+tran(P52,dRPIC)+[   Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддды])
      mon_drk([                                                                                                                                 ])
      mon_drk([1)Ilekro&_c. jest mowa o urz&_e.dzie skarbowym-oznacza to urz&_a.d skarbowy,kt&_o.rym kieruje w&_l.a&_s.ciwy dla podatnika naczelnik urz&_e.du        ])
      mon_drk([  skarbowego                                                                                                                     ])
      mon_drk([                                                                                                                                 ])
      mon_drk([2)W poz.19 nale&_z.y r&_o.wnie&_z. wykaza&_c. kwoty zwi&_e.kszaj&_a.ce przych&_o.d z tytu&_l.u utraty przez podat.prawa do ulg inwestyc.,w zwi&_a.zku z art7])
      mon_drk([  ust.19i20 ustawy z dnia 9.XI.2000r.o zmianie ustawy o pod.doch.od os&_o.b fiz.oraz o zm.niekt&_o.rych innych ustaw(Dz.U.Nr104poz1104,])
      mon_drk([  z p&_o.&_x.n.zm.)                                                                                                                    ])
      mon_drk([                                                                                                                                 ])
      mon_drk([3)Odliczenie nie dotyczy sk&_l.adek, kt&_o.rych podstaw&_e. wymiaru stanowi doch&_o.d (przych&_o.d) wolny od podatku na podstawie art.21,52,52a ])
      mon_drk([  i 52c ustawy,oraz sk&_l.adek,kt&_o.rych podstaw&_e. wymiaru stanowi doch&_o.d, od kt&_o.rego na podstawie przepis&_o.w ustawy z dnia 29.08.1997r.])
      mon_drk([  -Ordynacja podatkowa (Dz.U.z 2005r. Nr 8, poz.60, z p&_o.&_x.n.zm.) zaniechano poboru podatku.                                     ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                  PIT-5L (3)  1/3])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё E.   DOCH&__O.D PO ODLICZENIACH                                                                                                   Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁDoch&_o.d po odliczeniach strat i skladek                                                                Ё25.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.21 nale&_z.y odj&_a.&_c. kwot&_e. z pozycji 23 i 24.                                               Ё      ]+tran(P77,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё F. USTALENIE PODSTAWY OBLICZENIA PODATKU                                                                                      Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwoty zwi&_e.kszaj&_a.ce podstaw&_e. opodatkowania/zmniejszaj&_a.ce strat&_e. z tytu&_l.u utraty prawa do:              Ё26.                  Ё])
      mon_drk([Ё  Ё-zwolnienia-na podstawie przepis&_o.w wykonawczych do ustawy z dnia 20.10.1994r. o SSE (Dz.U.Nr 123,     Ё                     Ё])
      mon_drk([Ё  Ё poz.600,z p&_o.&_x.n.zm.) lub art.21 ust.5b i 5c ustawy.                                                   Ё      ]+tran(P75,dRPIC)+[   Ё])
      mon_drk([Ё  Ё-ulg inwest.-na podstawie przepis&_o.w rozporz&_a.dzenia RM z dnia 24.01.1995 (Dz.U.Nr 14, poz.63,z p&_o.&_x.n.zm)Ё                     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodstawa obliczenia podatku                                                                           Ё27.                  Ё])
      mon_drk([Ё  Ё(po zaokr&_a.gleniu do pe&_l.nych z&_l.otych)                                                                  Ё      ]+tran(P777,dRPIC)+[   Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G. OBLICZENIE NALE&__Z.NEGO PODATKU                                                                                               Ё])
      mon_drk([цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё G.1. OBLICZENIE PODATKU                                                                                                       Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodatek od podstawy z poz.27 obliczony wed&_l.ug zasad okre&_s.lonych w art.30c ustawy                      Ё28.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё      ]+tran(P79,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G.2.ODLICZENIE OD PODATKU                                                                                                     Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSk&_l.adka na ubezpieczenie zdrowotne, o kt&_o.rej mowa w art.27b ust.1 pkt 1 ustawy,z zastrze&_z.eniem art.27bЁ29.                  Ё])
      mon_drk([Ё  Ёust.2 ustawy 3), op&_l.acona od pocz&_a.tku roku                                                            Ё      ]+tran(p80,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G.3.OBLICZENIE NALE&__Z.NEJ ZALICZKI                                                                                              Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodatek po odliczeniach od pocz&_a.tku roku                                                              Ё30.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.28 nale&_z.y odj&_a.&_c. kwot&_e. z poz.29. Je&_z.eli r&_o.&_z.nica jest liczb&_a. ujemn&_a., wpisa&_c. 0            Ё      ]+tran(P85,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSuma nale&_z.nych zaliczek za poprzednie miesi&_a.ce. Nale&_z.y wpisa&_c. kwot&_e. z poz."Suma nale&_z.nych zaliczek od Ё31.                  Ё])
      mon_drk([Ё  Ёpocz&_a.tku roku" z pop.mie.Sk&_l.adaj&_a.c deklaracje po raz pierwszy w danym roku podatkowym nale&_z.y wpisa&_c. 0.Ё      ]+tran(P92,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNale&_z.na zaliczka za miesi&_a.c (po zaokr&_a.gleniu do pe&_l.nych z&_l.otych)                                      Ё32.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.30 nale&_z.y odj&_a.&_c. kwot&_e. z poz.31. Je&_z.eli r&_o.&_z.nica jest liczb&_a. ujemn&_a., nale&_z.y wpisa&_c. 0     Ё      ]+tran(P93,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSuma nale&_z.nych zaliczek od pocz&_a.tku roku                                                              Ё33.                  Ё])
      mon_drk([Ё  ЁSuma kwot z poz.31 i 32                                                                               Ё      ]+tran(p94,dRPIC)+[   Ё])
      mon_drk([цддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё G.4.OGRANICZENIE POBORU ZALICZEK-na podstawie art.22 par.2a ustawy z dnia 29.08.1997r. Ordynacja Podatkowa (Dz.U.z 2005 nr 8  Ё])
      mon_drk([Ё     poz.60,  z p&_o.&_x.n.zm.)                                                                                                      Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё34.Numer(-y) decyzji organu podatkowego                      Ё35.Data(-y) decyzji organu podatkowego (dzie&_n.-miesi&_a.c-rok)    Ё])
      mon_drk([Ё  Ё                                                             Ё                                                              Ё])
      mon_drk([Ё  Ё          ]+padc(rozrzut(alltrim(P884)),40)+[           Ё          ]+p886+[                                  Ё])
      mon_drk([Ё  Ё                                                             Ё                                                              Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota wynikaj&_a.ca z decyzji organu podatkowego                                                         Ё36.   ]+tran(p885,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota zrealizowana w poprzednich miesi&_a.cach                                                           Ё37.   ]+tran(p887,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota do zrealizowania w niniejszej deklaracji                                                        Ё38.                  Ё])
      mon_drk([Ё  ЁPodana kwota nie mo&_z.e przekroczy&_c. kwoty wykazanej w poz."Nale&_z.na zaliczka za miesi&_a.c"                 Ё      ]+tran(p888,dRPIC)+[   Ё])
      mon_drk([цддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё G.5.OBLICZENIE ZOBOWI&__A.ZANIA PRZYPADAJ&__A.CEGO DO ZAP&__L.ATY                                                                         Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁZaliczka po ograniczeniu                                                                              Ё39.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.32 nale&_z.y odj&_a.&_c. kwot&_e. z poz.38                                                         Ё      ]+tran(P889,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNale&_z.ny zrycza&_l.towany podatek dochodowy od dochodu z remanentu likwidacyjnego                         Ё40.                  Ё])
      mon_drk([Ё  ЁKwota z poz.11 za&_l.&_a.cznika PIT-5/X wype&_l.nia si&_e. tylko w miesi&_a.cu likwidacji dzia&_l.alno&_s.ci gospodarczej  Ё      ]+tran(P88,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota do zap&_l.aty *)                                                                                   Ё41.                  Ё])
      mon_drk([Ё  ЁSuma kwot z pozycji 39 i 40                                                                           Ё      ]+tran(P89,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota odsetek naliczonych od dnia zaliczenia do koszt&_o.w uzyskania przychod&_o.w wydatk&_o.w na nabycie lub  Ё42.                  Ё])
      mon_drk([Ё  Ёwytworzenie we w&_l.asnym zakresie sk&_l.adnik&_o.w maj&_a.tku do dnia, w kt&_o.rym okres ich u&_z.ywania przekroczy&_l.   Ё      ]+tran(P90,dRPIC)+[   Ё])
      mon_drk([Ё  Ёrok lub do dnia zaliczenia ich do &_s.rodk&_o.w trwa&_l.ych lub warto&_s.ci niematerialnych i prawnych - art.22e  Ё                     Ё])
      mon_drk([Ё  Ёust.1 pkt 4 i ust.2 ustawy *)                                                                         Ё                     Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддды])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([                                                                                                                                 ])
      mon_drk([ PIT-5L (3)  2/3                                                                                                                 ])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё H. POZAROLNICZA DZIA&__L.ALNO&__S.&__C. GOSPODARCZA (R&__O.WNIE&__Z. UDZIA&__L. W SP&__O.&__L.KACH NIE MAJ&__A.CYCH OSOBOWO&__S.CI PRAWNEJ)                           Ё])
      mon_drk([Ё  зддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Ё 43. Numer identyfikacyjny       ]+dzial_g[1,1]+[  Ё44. Identyfikator REGON             ]+dzial_g[1,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё45. Nazwa pe&_l.na                                                 Ё46. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[1,3],60)+[  Ё    ]+padc(dzial_g[1,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё47. Udzia&_l. w %          Ё48. Przych&_o.d            Ё49. Koszty              Ё50. Doch&_o.d              Ё51. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[1,5],3)+[     Ё     ]+tran(dzial_g[1,6],dRPICe)+[     Ё     ]+tran(dzial_g[1,7],dRPICe)+[     Ё       ]+tran(dzial_g[1,8],dRPIC)+[     Ё       ]+tran(dzial_g[1,9],dRPIC)+[     Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё2.Ё 52. Numer identyfikacyjny       ]+dzial_g[2,1]+[  Ё53. Identyfikator REGON             ]+dzial_g[2,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё54..Nazwa pe&_l.na                                                 Ё55. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[2,3],60)+[  Ё    ]+padc(dzial_g[2,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 56. Udzia&_l. w %         Ё57. Przych&_o.d            Ё58. Koszty              Ё59. Doch&_o.d              Ё60. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[2,5],3)+[     Ё     ]+tran(dzial_g[2,6],dRPICe)+[     Ё     ]+tran(dzial_g[2,7],dRPICe)+[     Ё       ]+tran(dzial_g[2,8],dRPIC)+[     Ё       ]+tran(dzial_g[2,9],dRPIC)+[     Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё3.Ё 61. Numer identyfikacyjny       ]+dzial_g[3,1]+[  Ё62. Identyfikator REGON             ]+dzial_g[3,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё63..Nazwa pe&_l.na                                                 Ё64. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[3,3],60)+[  Ё    ]+padc(dzial_g[3,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 65. Udzia&_l. w %         Ё66. Przych&_o.d            Ё67. Koszty              Ё68. Doch&_o.d              Ё69. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[3,5],3)+[     Ё     ]+tran(dzial_g[3,6],dRPICe)+[     Ё     ]+tran(dzial_g[3,7],dRPICe)+[     Ё       ]+tran(dzial_g[3,8],dRPIC)+[     Ё       ]+tran(dzial_g[3,9],dRPIC)+[     Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё4.Ё 70. Numer identyfikacyjny       ]+dzial_g[4,1]+[  Ё71. Identyfikator REGON             ]+dzial_g[4,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё72..Nazwa pe&_l.na                                                 Ё73. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[4,3],60)+[  Ё    ]+padc(dzial_g[4,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 74. Udzia&_l. w %         Ё75. Przych&_o.d            Ё76. Koszty              Ё77. Doch&_o.d              Ё78. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[4,5],3)+[     Ё     ]+tran(dzial_g[4,6],dRPICe)+[     Ё     ]+tran(dzial_g[4,7],dRPICe)+[     Ё       ]+tran(dzial_g[4,8],dRPIC)+[     Ё       ]+tran(dzial_g[4,9],dRPIC)+[     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╪])
      mon_drk([Ё I. INFORMACJA O ZA&__L.&__A.CZNIKACH                                                                                                  Ё])
      mon_drk([Ё    Nale&_z.y poda&_c. liczb&_e. do&_l.&_a.czonych formularzy o podanym symbolu (remanent&_o.w)                                                  Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё79. PIT-5/A                       Ё80. PIT-5/X                      Ё81. Remanent likwidacyjny                              Ё])
      mon_drk([Ё  Ё                                  Ё                                 Ё                                                       Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё J. O&__S.WIADCZENIE I PODPIS PODATNIKA                                                                                            Ё])
      mon_drk([Ё    O&_s.wiadczam, &_z.e s&_a. mi znane przepisy Kodeksu karnego skarbowego o odpowiedzialno&_s.ci za podanie danych niezgodnie z          Ё])
      mon_drk([Ё    rzeczywisto&_s.ci&_a. i przez to nara&_z.enie na uszczuplenie podatku.                                                              Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё82. Podpis podatnika                                                                                                        Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё K. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё83. Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё84. Identyfikator przyjmuj&_a.cego formularz                     Ё85. Podpis przyjmujacego formularz                           Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([                                                           *) POUCZENIE])
      mon_drk([W przypadku niewp&_l.acenia w obowi&_a.zuj&_a.cym terminie kwot z poz.41 i 42 lub wp&_l.acenia ich w niepe&_l.nej wysoko&_s.ci, niniejsza          ])
      mon_drk([deklaracja stanowi podstaw&_e. do wystawienia tytu&_l.u wykonawczego, zgodnie z przepisami ustawy z dnia 17 czerwca 1966r.             ])
      mon_drk([o post&_e.powaniu egzekucyjnym w administracji (Dz.U.z 2005r.Nr 229, poz.1954 z p&_o.&_x.n.zm.).                                          ])
      mon_drk([                                                                                                                   PIT-5L (3) 3/3])
      mon_drk([Ч])
end
