/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2020  GM Systems Micha┬ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      rRPIC1='@E 999 999   '
      rRPIC2='@E 99 999.99'
      rRPIC3='@E 9 999.99'
      rRPIC4='@E     999   '
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([Ж]+procname())
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддбддддддддд©])
      mon_drk([Ё1.Identyfikator podatkowy NIP p&_l.atnika    Ё2.Nr dokumentu             Ё3.Status Ё])
      mon_drk([Ё             ]                    +rozrzut(P1)+[   Ё                           Ё         Ё])
      mon_drk([юддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддаддддддддды])
      mon_drk([P I T - 4 R])
      mon_drk([       D E K L A R A C J A   R O C Z N A   O   P O B R A N Y C H   Z A L I C Z K A C H ])
      mon_drk([                     N A   P O D A T E K   D O C H O D O W Y ])
      mon_drk([                                 здддддддддддддддддд©])
      mon_drk([                                 Ё4.Rok             Ё])
      mon_drk([                              ZA Ё       ]+p4+[   Ё])
      mon_drk([                                 юдддддддддддддддддды])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([ЁPodstawa prawna:   Art.38 ust.1a, art.42 ust.1a i art.42e ust.5 ustawy z dnia 26.07.1991r.o podatku dochodowym od os&_o.b fizyczn.Ё])
      mon_drk([Ё                   (Dz.U.z 2012 r. poz.361 z p&_o.&_x.n.zm.), zwanej dalej "ustaw&_a.";art.35a ust.4a ustawy,w brzmieniu obowi&_a.zuj&_a.cym  Ё])
      mon_drk([Ё                   przed dniem 26.10.2007r. 1)                                                                                 Ё])
      mon_drk([ЁSk&_l.adaj&_a.cy:        P&_l.atnik podatku dochodowego od os&_o.b fizycznych.                                                             Ё])
      mon_drk([ЁTerminy sk&_l.adania: Do ko&_n.ca stycznia roku nast&_e.puj&_a.cego po roku podatkowym. W przypadku zaprzestania dzia&_l.alno&_s.ci przez        Ё])
      mon_drk([Ё                   p&_l.atnik&_o.w o kt&_o.rych mowa w art.31,33-35, art.41 i 42e ustawy, przed tym terminem - do dnia zaprzestania tej Ё])
      mon_drk([Ё                   dzia&_l.alno&_s.ci, a w przypadku p&_l.atnika, o kt&_o.rym mowa w art.35a 1) ustawy, kt&_o.ry zaprzesta&_l. poboru zaliczek   Ё])
      mon_drk([Ё                   przed tym terminem - do dnia ustania obowi&_a.zku poboru tych zaliczek.                                        Ё])
      mon_drk([ЁMiejsce sk&_l.adania: Urz&_a.d skarbowy    wed&_l.ug miejsca zamieszkania p&_l.atnika, a je&_z.eli p&_l.atnik nie jest osob&_a. fizyczn&_a., wed&_l.ug    Ё])
      mon_drk([Ё                   siedziby b&_a.d&_x. miejsca prowadzenia dzia&_l.alno&_s.ci, gdy p&_l.atnik nie posiada siedziby.                           Ё])
      mon_drk([ц*******************************************************************************************************************************Ё])
      mon_drk([Ё A. MIEJSCE SK&__L.ADANIA DEKLARACJI                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё5.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest deklaracja 2)                                                                  Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P6)),120)+[   Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё6.Cel z&_l.o&_z.enia formularza  (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                     Ё])
      mon_drk('Ё  Ё                            '+iif(zDEKLKOR="D","[XX]","[  ]")+'  1.zlozenie deklaracji                    '+iif(zDEKLKOR<>"D","[XX]","[  ]")+'  2.korekta deklaracji 3)                    Ё')
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё B. DANE IDENTYFIKACYJNE P&__L.ATNIKA   * - dotyczy p&_l.atnika nieb&_e.d&_a.cego osob&_a. fizyczn&_a.   ** - dotyczy p&_l.atnika b&_e.d&_a.cego osob&_a. fizyczn&_a.   Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё7.Rodzaj p&_l.atnika  (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                             Ё])
      mon_drk([Ё  Ё                           ]+iif(spolka_,'[XX]','[  ]')+[  1.P&_l.atnik nie b&_e.d&_a.cy osob&_a. fizyczn&_a.          ]+iif(.not.spolka_,'[XX]','[  ]')+[  2.Osoba fizyczna                        Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё8.Nazwa pe&_l.na, REGON*   /   Nazwisko, pierwsze imi&_e., data urodzenia **                                                      Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P8)),120)+[   Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё C. WYKAZ NALE&__Z.NYCH ZALICZEK NA PODATEK DOCHODOWY ZA POSZCZEG&__O.LNE MIESI&__A.CE ROKU PODATKOWEGO 4)                                 Ё])
      mon_drk([цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё 1.Zaliczki na podatek obliczone przez p&_l.atnik&_o.w,o kt&_o.rych mowa w art.31 i art.42e ust.1,od dochod&_o.w wymienionych w tych przep.Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё         Liczba podatnik&_o.w           Ё 9.           Ё10.           Ё11.           Ё12.           Ё13.           Ё14.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1a01,rRPIC4)+[  Ё  ]+tran(z1a02,rRPIC4)+[  Ё  ]+tran(z1a03,rRPIC4)+[  Ё  ]+tran(z1a04,rRPIC4)+[  Ё  ]+tran(z1a05,rRPIC4)+[  Ё  ]+tran(z1a06,rRPIC4)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё15.           Ё16.           Ё17.           Ё18.           Ё19.           Ё20.           Ё])
      mon_drk([Ё         Nale&_z.ne zaliczki            Ё  ]+tran(z1b01,rRPIC1)+[  Ё  ]+tran(z1b02,rRPIC1)+[  Ё  ]+tran(z1b03,rRPIC1)+[  Ё  ]+tran(z1b04,rRPIC1)+[  Ё  ]+tran(z1b05,rRPIC1)+[  Ё  ]+tran(z1b06,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё         Liczba podatnik&_o.w           Ё21.           Ё22.           Ё23.           Ё24.           Ё25.           Ё26.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1a07,rRPIC4)+[  Ё  ]+tran(z1a08,rRPIC4)+[  Ё  ]+tran(z1a09,rRPIC4)+[  Ё  ]+tran(z1a10,rRPIC4)+[  Ё  ]+tran(z1a11,rRPIC4)+[  Ё  ]+tran(z1a12,rRPIC4)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё27.           Ё28.           Ё29.           Ё30.           Ё31.           Ё32.           Ё])
      mon_drk([Ё         Nale&_z.ne zaliczki            Ё  ]+tran(z1b07,rRPIC1)+[  Ё  ]+tran(z1b08,rRPIC1)+[  Ё  ]+tran(z1b09,rRPIC1)+[  Ё  ]+tran(z1b10,rRPIC1)+[  Ё  ]+tran(z1b11,rRPIC1)+[  Ё  ]+tran(z1b12,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 2.Zaliczki na podatek obliczone przez p&_l.atnik&_o.w,o kt&_o.rych mowa w art.33-35 ustawy, od dochod&_o.w wymienionych w tych przepisach Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё33.           Ё34.           Ё35.           Ё36.           Ё37.           Ё38.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z201,rRPIC1)+[  Ё  ]+tran(z202,rRPIC1)+[  Ё  ]+tran(z203,rRPIC1)+[  Ё  ]+tran(z204,rRPIC1)+[  Ё  ]+tran(z205,rRPIC1)+[  Ё  ]+tran(z206,rRPIC1)+[  Ё])
      mon_drk([Ё         Nale&_z.ne zaliczki            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё39.           Ё40.           Ё41.           Ё42.           Ё43.           Ё44.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z207,rRPIC1)+[  Ё  ]+tran(z208,rRPIC1)+[  Ё  ]+tran(z209,rRPIC1)+[  Ё  ]+tran(z210,rRPIC1)+[  Ё  ]+tran(z211,rRPIC1)+[  Ё  ]+tran(z212,rRPIC1)+[  Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([1) Art.35a ustawy zostal uchylony z dn.26.10.2007r. ustaw&_a. z dnia 24.08.2007r. o zmianie ustawy o promocji zatrudnienia i insty- ])
      mon_drk([   tucjach rynku pracy oraz o zmianie niektorych innych ustaw (Dz.U.Nr 176,poz.1243).Uchylony przepis na mocy art.7 ust.7 powola-])
      mon_drk([   nej ustawy ma zastosowanie do platnikow do czasu obowiazywania umowy aktywizacyjnej zawartej przed dniem 26.10.2007r.         ])
      mon_drk([2) Ilekro&_c. jest mowa o urz&_e.dzie skarbowym-oznacza to urz&_a.d, kt&_o.rym kieruje w&_l.a&_s.ciwy dla p&_l.atnika naczelnik urz&_e.du skarbowego.    ])
      mon_drk([3) Zgodnie z art.81 ustawy z dnia 29 sierpnia 1997r.-Ordynacja podatkowa(Dz.U.z2012r.poz.749,z p&_o.&_z.n.zm.),zwanej dalej "Ordynacj&_a. ])
      mon_drk([   podatkow&_a.",p&_l.atnik mo&_z.e skorygowa&_c. z&_l.o&_z.on&_a. deklaracj&_e. przez z&_l.o&_z.enie deklar.koryg.wraz z do&_l..pisemn.uzasad.przyczyn korekty.  ])
      mon_drk([4) Zaliczki na podatek,pomniejszone o skladki na ubezpieczenie zdrowotne zgodnie z przepisami ustawy                             ])
      mon_drk([                                                                                                                   PIT-4R (8) 1/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё 3.Zaliczki na podatek pobrane od &_s.wiadcze&_n. z tytu&_l.u dzia&_l.alno&_s.ci okre&_s.lonej w art.13 ustawy pkt 2 i 4-9 oraz art.18 ustawy 4) Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё45.           Ё46.           Ё47.           Ё48.           Ё49.           Ё50.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1001,rRPIC1)+[  Ё  ]+tran(z1002,rRPIC1)+[  Ё  ]+tran(z1003,rRPIC1)+[  Ё  ]+tran(z1004,rRPIC1)+[  Ё  ]+tran(z1005,rRPIC1)+[  Ё  ]+tran(z1006,rRPIC1)+[  Ё])
      mon_drk([Ё           Kwoty zaliczek            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё51.           Ё52.           Ё53.           Ё54.           Ё55.           Ё56.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1007,rRPIC1)+[  Ё  ]+tran(z1008,rRPIC1)+[  Ё  ]+tran(z1009,rRPIC1)+[  Ё  ]+tran(z1010,rRPIC1)+[  Ё  ]+tran(z1011,rRPIC1)+[  Ё  ]+tran(z1012,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 4.Zaliczki na podatek pobrane od innych nale&_z.no&_s.ci, w tym wynikaj&_a.cych z umowy aktywizacyjnej 4)                              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё57.           Ё58.           Ё59.           Ё60.           Ё61.           Ё62.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z901,rRPIC1)+[  Ё  ]+tran(z902,rRPIC1)+[  Ё  ]+tran(z903,rRPIC1)+[  Ё  ]+tran(z904,rRPIC1)+[  Ё  ]+tran(z905,rRPIC1)+[  Ё  ]+tran(z906,rRPIC1)+[  Ё])
      mon_drk([Ё            Kwoty zaliczek           цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё63.           Ё64.           Ё65.           Ё66.           Ё67.           Ё68.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z907,rRPIC1)+[  Ё  ]+tran(z908,rRPIC1)+[  Ё  ]+tran(z909,rRPIC1)+[  Ё  ]+tran(z910,rRPIC1)+[  Ё  ]+tran(z911,rRPIC1)+[  Ё  ]+tran(z912,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 5.Suma nale&_z.nych zaliczek za poszczeg&_o.lne miesi&_a.ce roku podatkowego wykazanych w wierszach 1 - 4                              Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё69.           Ё70.           Ё71.           Ё72.           Ё73.           Ё74.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z301,rRPIC1)+[  Ё  ]+tran(z302,rRPIC1)+[  Ё  ]+tran(z303,rRPIC1)+[  Ё  ]+tran(z304,rRPIC1)+[  Ё  ]+tran(z305,rRPIC1)+[  Ё  ]+tran(z306,rRPIC1)+[  Ё])
      mon_drk([Ё       Suma nale&_z.nych zaliczek       цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё75.           Ё76.           Ё77.           Ё78.           Ё79.           Ё80.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z307,rRPIC1)+[  Ё  ]+tran(z308,rRPIC1)+[  Ё  ]+tran(z309,rRPIC1)+[  Ё  ]+tran(z310,rRPIC1)+[  Ё  ]+tran(z311,rRPIC1)+[  Ё  ]+tran(z312,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 6.Zaliczki na podatek,kt&_o.rych pob&_o.r zosta&_l. ograniczony na podstawie art.32 ust.2 ustawy                                       Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё81.           Ё82.           Ё83.           Ё84.           Ё85.           Ё86.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z401,rRPIC1)+[  Ё  ]+tran(z402,rRPIC1)+[  Ё  ]+tran(z403,rRPIC1)+[  Ё  ]+tran(z404,rRPIC1)+[  Ё  ]+tran(z405,rRPIC1)+[  Ё  ]+tran(z406,rRPIC1)+[  Ё])
      mon_drk([Ё            Kwoty zaliczek           цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё87.           Ё88.           Ё89.           Ё90.           Ё91.           Ё92.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z407,rRPIC1)+[  Ё  ]+tran(z408,rRPIC1)+[  Ё  ]+tran(z409,rRPIC1)+[  Ё  ]+tran(z410,rRPIC1)+[  Ё  ]+tran(z411,rRPIC1)+[  Ё  ]+tran(z412,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 7.Zaliczki,kt&_o.re przypada&_l.y do pobrania w zwi&_a.zku z ograniczeniem poboru zaliczek w poprzednich miesi&_a.cach na podstawie       Ё])
      mon_drk([Ё   art.32 ust.2 ustawy                                                                                                         Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё93.           Ё94.           Ё95.           Ё96.           Ё97.           Ё98.           Ё])
      mon_drk([Ё                                     Ё  ]+tran(z501,rRPIC1)+[  Ё  ]+tran(z502,rRPIC1)+[  Ё  ]+tran(z503,rRPIC1)+[  Ё  ]+tran(z504,rRPIC1)+[  Ё  ]+tran(z505,rRPIC1)+[  Ё  ]+tran(z506,rRPIC1)+[  Ё])
      mon_drk([Ё            Kwoty zaliczek           цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё99.           Ё100.          Ё101.          Ё102.          Ё103.          Ё104.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z507,rRPIC1)+[  Ё  ]+tran(z508,rRPIC1)+[  Ё  ]+tran(z509,rRPIC1)+[  Ё  ]+tran(z510,rRPIC1)+[  Ё  ]+tran(z511,rRPIC1)+[  Ё  ]+tran(z512,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё 8.Dodatkowo pobrany podatek wynikaj&_a.cy z rozliczenia za rok ubieg&_l.y                                                           Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё105.          Ё106.          Ё107.          Ё108.          Ё. . . . . . . Ё. . . . . . . Ё])
      mon_drk([Ё                                     Ё  ]+tran(z601,rRPIC1)+[  Ё  ]+tran(z602,rRPIC1)+[  Ё  ]+tran(z603,rRPIC1)+[  Ё  ]+tran(z604,rRPIC1)+[  Ё . . . . . . .Ё . . . . . . .Ё])
      mon_drk([Ё            Kwoty podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё. . . . . . . Ё. . . . . . . Ё. . . . . . . Ё. . . . . . . Ё. . . . . . . Ё. . . . . . . Ё])
      mon_drk([Ё                                     Ё . . . . . . .Ё . . . . . . .Ё . . . . . . .Ё . . . . . . .Ё . . . . . . .Ё . . . . . . .Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([PIT-4R (8) 2/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё 9.Nadp&_l.aty wynikaj&_a.ce z rozliczenia za rok ubieg&_l.y oraz zwrot nadp&_l.at w got&_o.wce zaliczone na poczet nale&_z.nej zaliczki         Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё109.          Ё110.          Ё111.          Ё112.          Ё113.          Ё 114.         Ё])
      mon_drk([Ё      Kwoty nadp&_l.aty zaliczonej      Ё  ]+tran(z701,rRPIC1)+[  Ё  ]+tran(z702,rRPIC1)+[  Ё  ]+tran(z703,rRPIC1)+[  Ё  ]+tran(z704,rRPIC1)+[  Ё  ]+tran(z705,rRPIC1)+[  Ё  ]+tran(z706,rRPIC1)+[  Ё])
      mon_drk([Ё      oraz zwr&_o.conej w got&_o.wce       цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё115.          Ё116.          Ё117.          Ё118.          Ё119.          Ё120.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z707,rRPIC1)+[  Ё  ]+tran(z708,rRPIC1)+[  Ё  ]+tran(z709,rRPIC1)+[  Ё  ]+tran(z710,rRPIC1)+[  Ё  ]+tran(z711,rRPIC1)+[  Ё  ]+tran(z712,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё10.Pobrany podatek,przekazany na PFRON oraz zak&_l.adowy fundusz rehabilitacji os&_o.b niepe&_l.nosprawnych albo zak&_l.adowy fund.aktywno.Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё121.          Ё122.          Ё123.          Ё124.          Ё125.          Ё126.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z801,rRPIC1)+[  Ё  ]+tran(z802,rRPIC1)+[  Ё  ]+tran(z803,rRPIC1)+[  Ё  ]+tran(z804,rRPIC1)+[  Ё  ]+tran(z805,rRPIC1)+[  Ё  ]+tran(z806,rRPIC1)+[  Ё])
      mon_drk([Ё           Kwoty podatku             цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё127.          Ё128.          Ё129.          Ё130.          Ё131.          Ё132.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z807,rRPIC1)+[  Ё  ]+tran(z808,rRPIC1)+[  Ё  ]+tran(z809,rRPIC1)+[  Ё  ]+tran(z810,rRPIC1)+[  Ё  ]+tran(z811,rRPIC1)+[  Ё  ]+tran(z812,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё11.Pobrany podatek do przekazania do urz&_e.du skarbowego za poszczeg&_o.lne miesi&_a.ce roku podatkowego                               Ё])
      mon_drk([Ё   Od sumy kwot za poszczeg&_o.lne miesi&_a.ce z wiersza 3,5,6,9 i 10 nale&_z.y odpowiednio odj&_a.&_c. sum&_e. kwot z wierszy 4,7 i 8.          Ё])
      mon_drk([Ё   Je&_z.eli r&_o.&_z.nica w danym miesi&_a.cu jest liczb&_a. ujemn&_a., nale&_z.y wpisa&_c. 0.                                                        Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё133.          Ё134.          Ё135.          Ё136.          Ё137.          Ё138.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1101,rRPIC1)+[  Ё  ]+tran(z1102,rRPIC1)+[  Ё  ]+tran(z1103,rRPIC1)+[  Ё  ]+tran(z1104,rRPIC1)+[  Ё  ]+tran(z1105,rRPIC1)+[  Ё  ]+tran(z1106,rRPIC1)+[  Ё])
      mon_drk([Ё            Kwoty podatku            цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё139.          Ё140.          Ё141.          Ё142.          Ё143.          Ё144.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1107,rRPIC1)+[  Ё  ]+tran(z1108,rRPIC1)+[  Ё  ]+tran(z1109,rRPIC1)+[  Ё  ]+tran(z1110,rRPIC1)+[  Ё  ]+tran(z1111,rRPIC1)+[  Ё  ]+tran(z1112,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё12.Wynagrodzenie z tytu&_l.u terminowego wp&_l.acania podatku dochodowego za poszczeg&_o.lne miesi&_a.ce,zgodnie z art.28 Ordynacji podatk.Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё145.          Ё146.          Ё147.          Ё148.          Ё149.          Ё150.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1201,rRPIC1)+[  Ё  ]+tran(z1202,rRPIC1)+[  Ё  ]+tran(z1203,rRPIC1)+[  Ё  ]+tran(z1204,rRPIC1)+[  Ё  ]+tran(z1205,rRPIC1)+[  Ё  ]+tran(z1206,rRPIC1)+[  Ё])
      mon_drk([Ё          Kwoty wynagrodzenia        цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё151.          Ё152.          Ё153.          Ё154.          Ё155.          Ё156.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1207,rRPIC1)+[  Ё  ]+tran(z1208,rRPIC1)+[  Ё  ]+tran(z1209,rRPIC1)+[  Ё  ]+tran(z1210,rRPIC1)+[  Ё  ]+tran(z1211,rRPIC1)+[  Ё  ]+tran(z1212,rRPIC1)+[  Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддд╢])
      mon_drk([Ё13.Nale&_z.ne kwoty do wp&_l.aty za poszczeg&_o.lne miesi&_a.ce roku podatkowego                                                           Ё])
      mon_drk([Ё   Od kwot za poszczeg&_o.lne miesi&_a.ce z wiersza 11 nale&_z.y odpowiednio odj&_a.&_c. kwoty z wiersza 12. Je&_z.eli r&_o.&_z.nica w danym miesi&_a.cu  Ё])
      mon_drk([Ё   jest liczb&_a. ujemn&_a., nale&_z.y wpisa&_c. 0.                                                                                        Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбддддддддддддддбдддддддддддддд╢])
      mon_drk([Ё                                     Ё      I       Ё      II      Ё     III      Ё      IV      Ё      V       Ё      VI      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё157.          Ё158.          Ё159.          Ё160.          Ё161.          Ё162.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1301,rRPIC1)+[  Ё  ]+tran(z1302,rRPIC1)+[  Ё  ]+tran(z1303,rRPIC1)+[  Ё  ]+tran(z1304,rRPIC1)+[  Ё  ]+tran(z1305,rRPIC1)+[  Ё  ]+tran(z1306,rRPIC1)+[  Ё])
      mon_drk([Ё           Kwoty do wp&_l.aty *)        цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё     VII      Ё     VIII     Ё      IX      Ё      X       Ё      XI      Ё     XII      Ё])
      mon_drk([Ё                                     цддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддеддддддддддддддедддддддддддддд╢])
      mon_drk([Ё                                     Ё163.          Ё164.          Ё165.          Ё166.          Ё167.          Ё168.          Ё])
      mon_drk([Ё                                     Ё  ]+tran(z1307,rRPIC1)+[  Ё  ]+tran(z1308,rRPIC1)+[  Ё  ]+tran(z1309,rRPIC1)+[  Ё  ]+tran(z1310,rRPIC1)+[  Ё  ]+tran(z1311,rRPIC1)+[  Ё  ]+tran(z1312,rRPIC1)+[  Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддаддддддддддддддадддддддддддддды])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([                                                                                                                   PIT-4R (8) 3/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([ЁD.WYJA&__S.NIENIE DOTYCZ&__A.CE WP&__L.ATY                                                                                                 Ё])
      mon_drk([Ё                                                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё169.Wyja&_s.nienie r&_o.&_z.nicy pomi&_e.dzy kwot&_a. pobranego podatku a kwot&_a. wp&_l.aconego podatku                                         Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё E. PODPIS P&__L.ATNIKA LUB OSOBY WYZNACZONEJ DO OBLICZENIA I POBRANIA PODATKU / PE&__L.NOMOCNIKA P&__L.ATNIKA                             Ё])
      mon_drk([Ё                                                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё170.Imi&_e.                               Ё171.Nazwisko                           Ё172.Podpis i piecz&_a.tka                      Ё])
      mon_drk([Ё  Ё                                       Ё                                       Ё                                            Ё])
      mon_drk([Ё  Ё            ]+zDEKLIMIE+[            Ё          ]+zDEKLNAZWI+[         Ё                                            Ё])
      mon_drk([Ё  Ё                                       Ё                                       Ё                                            Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё F. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё                                                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё173.Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё............................................................................................................................Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё174.Identyfikator przyjmuj&_a.cego formularz                     Ё175.Podpis przyjmuj&_a.cego formularz                           Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([])
      mon_drk([                                               *) Pouczenie])
      mon_drk([])
      mon_drk([   W przypadku niewp&_l.acenia w obowi&_a.zuj&_a.cym terminie kwoty z poz.od 157 do 168 lub wp&_l.acenia ich w niepe&_l.nej wysoko&_s.ci, niniejsza])
      mon_drk([   deklaracja stanowi podstaw&_e. do wystawienia tytu&_l.u wykonawczego, zgodnie z przepisami ustawy z dnia 17.06.1966r. o post&_e.powaniu])
      mon_drk([   egzekucyjnym w administracji (Dz.U.z 2012r. poz.1015,z p&_o.&_x.n.zm.)])
      mon_drk([])
      mon_drk([   Za uchybienie obowi&_a.zkom p&_l.atnika grozi odpowiedzialno&_s.&_c. przewidziana w Kodeksie karnym skarbowym. ])
      mon_drk([])
      mon_drk([                                                 Obja&_s.nienia])
      mon_drk([])
      mon_drk([   Kwoty podatku i wynagrodzenia przys&_l.uguj&_a.cego p&_l.atnikom z tytu&_l.u terminowego wp&_l.acenia podatku,zgodnie z art.63 Ordynacji     ])
      mon_drk([   podatkowej,zaokr&_a.gla si&_e. do pe&_l.nych z&_l.otych.                                                                                  ])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([PIT-4R (8) 4/4])
      mon_drk([Ч])
end


