/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2019  GM Systems Micha┬ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([Ж]+procname())
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддбддддддддд©])
      mon_drk([Ё1.Numer identyfikacji Podatkowej          Ё2.Nr dokumentu             Ё3.Status Ё])
      mon_drk([Ё             ]+substr(P3,1,7)+[-]+substr(P3,8,7)+[-]+substr(P3,15,5)+[-]+substr(P3,20)+[   Ё                           Ё         Ё])
      mon_drk([юддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддаддддддддды])
      mon_drk([P I T - 5])
      mon_drk([])
      mon_drk([    D E K L A R A C J A   N A   Z A L I C Z K &__E.   M I E S I &__E. C Z N &__A.])
      mon_drk([                N A   P O D A T E K   D O C H O D O W Y])
      mon_drk([                       здддддддддддддддддд©])
      mon_drk([                  Z A  Ё4.Miesi&_a.c-rok     Ё])
      mon_drk([                       Ё   ]+substr(p4,1,5)+[-]+substr(p4,7)+[ Ё])
      mon_drk([                       юдддддддддддддддддды])
      mon_drk([])
      mon_drk([ Formularz jest przeznaczony dla podatnik&_o.w:])
      mon_drk([ - prowadz&_a.cych dzia&_l.alno&_s.&_c. gospodarcz&_a.])
      mon_drk([ - osi&_a.gaj&_a.cych przychody z najmu, podnajmu lub dzier&_z.awy oraz innych um&_o.w o podobnym charakterze.])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([ЁPodstawa prawna  :Art.44 ust.6 ustawy z dnia 26 lipca 1991r. o podatku dochodowym od os&_o.b fizycznych (Dz.U.z 2000r.Nr14,poz.176Ё])
      mon_drk([Ё                  z p&_o.&_x.niejszymi zmianami), zwanej dalej "ustaw&_a.".                                                             Ё])
      mon_drk([ЁSk&_l.adaj&_a.cy       :Podatnik podatku dochodowego od os&_o.b fizycznych.                                                             Ё])
      mon_drk([ЁTermin sk&_l.adania :Za miesi&_a.ce od stycznia do listopada - do dnia 20 ka&_z.dego miesi&_a.ca za miesi&_a.c poprzedni (zaliczke za grudzie&_n.Ё])
      mon_drk([Ё                  w wysoko&_s.ci nale&_z.nej za listopad uiszcza si&_e. w terminie do 20 grudnia, bez sk&_l.adania deklaracji).            Ё])
      mon_drk([ЁMiejsce sk&_l.adania:Urz&_a.d skarbowy w&_l.a&_s.ciwy wg miejsca zamieszkania podatnika.                                                   Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё A. MIEJSCE SK&__L.ADANIA DEKLARACJI                                                                                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё5.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest deklaracja                                                                     Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P5)),120)+[   Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё B. DANE PODATNIKA                                                                                                             Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё B.1. DANE IDENTYFIKACYJNE                                                                                                     Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё6.Nazwisko      ]+padc(rozrzut(alltrim(p7)),40)+space(68)+[Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё7.Pierwsze imie  ]+padc(rozrzut(alltrim(p8)),40)+[     Ё8.Data urodz.(dzien-miesiac-rok) ]+substr(p12,1,5)+[-]+substr(p12,6,5)+[-]+substr(p12,11)+space(8)+[Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё B.2. ADRES ZAMIESZKANIA                                                                                                       Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 9.Kraj         P O L S K A     Ё 10.Wojew&_o.dz. ]+padc(alltrim(P15),35)+[ Ё11.Powiat]+padc(alltrim(P15a),30)+[ Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддаддддбдддддддддддддддддддддддддддддддддддддддбдддддадддддддддддддддддбдддддддддддддддддддддд╢])
      mon_drk([Ё  Ё12.Gmina]+padc(alltrim(P16),29)+[Ё13.Ulica ]+padc(rozrzut(alltrim(p17)),30)+[Ё14.Nr domu  ]+padc(alltrim(P18),10)+[ Ё15.Nr lokal.]+padc(alltrim(P19),10)+[Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддадддддддддддддддддддбдддддддддддддддддддаддддбддддддддддддддддддадддддддддддддддддддддд╢])
      mon_drk([Ё  Ё16.Miejscowo&_s.&_c.  ]+padc(rozrzut(alltrim(p20)),40)+[ Ё17.Kod pocztowy  ]+P21+[ Ё18.Poczta  ]+padc(alltrim(p22),25)+[     Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё C. USTALENIE DOCHODU/STRATY                                                                                                   Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддбдддддддддддддддддддддбдддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё          &__X.r&_o.d&_l.o przychod&_o.w            Ё      Przych&_o.d       ЁKoszty uzysk.przycho.Ё    Doch&_o.d (b-c)     Ё    Strata (c-b)     Ё])
      mon_drk([Ё                  a                    Ё          b          Ё          c          Ё          d          Ё          e          Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё1.Pozarolnicza dzia&_l.alno&_s.&_c. gospodarcza Ё19.                  Ё20.                  Ё21.                  Ё22.                  Ё])
      mon_drk([Ё                                       Ё                     Ё                     Ё                     Ё                     Ё])
      mon_drk([Ё                                       Ё  ]+tran(p27,dRPICe)+[     Ё  ]+tran(p28,dRPICe)+[     Ё    ]+tran(p29,dRPIC)+[     Ё    ]+tran(p30,dRPIC)+[     Ё])
      mon_drk([цдддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддедддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё2.Najem,podnajem lub dzier&_z.awa oraz    Ё23.                  Ё24.                  Ё25.                  Ё26.                  Ё])
      mon_drk([Ё  inne umowy o podobnym charakterze    Ё                     Ё                     Ё                     Ё                     Ё])
      mon_drk([Ё                                       Ё  ]+tran(p31,dRPICe)+[     Ё  ]+tran(p32,dRPICe)+[     Ё    ]+tran(p33,dRPIC)+[     Ё    ]+tran(p34,dRPIC)+[     Ё])
      mon_drk([имммммммммммммммммммммммммммммммммммммммкмммммммммммммммммммммкмммммммммммммммммммммкмммммммммммммммммммммкммммммммммммммммммммм╩])
      mon_drk([╨  RAZEM                                ╨27.                  ╨28.                  ╨29.                  ╨30.                  ╨])
      mon_drk([╨  Suma kwot z wierszy od 1 i 2         ╨  ]+tran(p45,dRPICe)+[     ╨  ]+tran(p46,dRPICe)+[     ╨    ]+tran(p47,dRPIC)+[     ╨    ]+tran(p48,dRPIC)+[     ╨])
      mon_drk([хмммммммммммммммммммммммммммммммммммммммймммммммммммммммммммммймммммммммммммммммммммймммммммммммммммммммммйммммммммммммммммммммм╪])
      mon_drk([Ё D. DOCHOD PO ODLICZENIU DOCHODU ZWOLNIONEGO I STRAT                                                                           Ё])
      mon_drk([Ё    Suma odliczen nie moze przekroczyc kwoty dochodu z poz.29                                                                  Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё Doch&_o.d zwolniony od podatku-na podstawie art.21 ust.1 pkt63a ustawy                                  Ё31.                  Ё])
      mon_drk([Ё  Ё Zwolnienie przysluguje wylacznie z tytulu dochodow uzyskanych z dzialalnosci gospodarczej prowadzonejЁ                     Ё])
      mon_drk([Ё  Ё na terenie SSE.Pozycji tej nie wypelniaja podatnicy korzystajacy ze zwolnienia,o ktorym mowa w poz.46Ё      ]+tran(P50,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё Straty z lat ubieglych zgodnie z art.9 ust.3 i 3a ustawy z uwzglednieniem art.3 ustawy z dn11.08.2001Ё32.                  Ё])
      mon_drk([Ё  Ё o szczegolnych rozwiazaniach prawnych zwiazanych z usuwaniem skutkow powodzi z lipca i sierpnia 2001rЁ                     Ё])
      mon_drk([Ё  Ё oraz o zmianie niektorych ustaw (Dz.U.z 2001r. Nr84, poz.907, z pozniejszymi zmianami)               Ё      ]+tran(P51,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё Dochod po odliczeniu dochodu zwolnionego i strat                                                     Ё33.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё Od kwoty z poz.29 nalezy odjac kwoty z poz.31 i 32                                                   Ё      ]+tran(P52,dRPIC)+[   Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддды])
      mon_drk([])
      mon_drk([])
      mon_drk([                                                                                                                  PIT-5 (12)  1/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё E. ODLICZENIA OD DOCHODU                                                                                                      Ё])
      mon_drk([Ё    Suma kwot z cz&_e.&_s.ci od E.1 do E.3 oraz F i G nie mo&_z.e przekroczy&_c. kwoty z poz.33.                                           Ё])
      mon_drk([цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё E.1. ODLICZENIA OD DOCHODU - na podstawie art.26 ust.1 pkt2-6 i 9-10 ustawy                                                   Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Skladki okreslone w przepisach o systemie ubezpieczen spolecznych, zaplacone bezposrednio na wlasne Ё34.                  Ё])
      mon_drk([Ё  Ё  ubezpieczenie emerytalne,rentowe,chorobowe oraz wypadkowe podatnika oraz osob z nim wspolpracujacychЁ                     Ё])
      mon_drk([Ё  Ё  jezeli nie zostaly zaliczone do kosztow uzyskania przychodow (na podstawie art.26ust.1pkt2lit.a) 3) Ё      ]+tran(P54,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё2.Odliczenia od dochodu na podstawie art.26 ust.1 pkt3-6 i 9-10 ustawy                                Ё35.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё      ]+tran(P55,dRPIC)+[   Ё])
      mon_drk([цддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё E.2. ODLICZENIA OD DOCHODU WYDATKOW MIESZKANIOWYCH - na podstawie art.3 ustawy z dnia 21.11.1996r. (Dz.U.z 1996r. nr137,      Ё])
      mon_drk([Ё      poz.638 z pozniejszymi zmianami), art.7 ust.12 i 13 ustawy z dnia 9.11.2000r. (Dz.U. z 2000r. nr 104, poz.1104, z pozn.  Ё])
      mon_drk([Ё      zmianami) oraz art.3 ustawy z dnia 21.11.2001r. (Dz.U.z 2001r. nr 134, poz.1509, z pozniejszymi zmianami)                Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Wydatki poniesione w latach ubieglych, ktore nie znalazly pokrycia w uzyskanych dochodach za te lataЁ36.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё      ]+tran(P64,dRPIC)+[   Ё])
      mon_drk([Ё  цдддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё2.Wydatki      Ё 37.Podac rodzaj:                                                                     Ё38.                  Ё])
      mon_drk([Ё  Ё  poniesione   Ё                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё  w roku       Ё            ]+padc(rozrzut(alltrim(P63o)),60)+[              Ё      ]+tran(P63,dRPIC)+[   Ё])
      mon_drk([Ё  Ё  podatkowym   Ё                                                                                      Ё                     Ё])
      mon_drk([цддадддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё E.3. INNE ODLICZENIA, NIE WYMIENIONE W CZESCIACH OD E.1 do E.2                                                                Ё])
      mon_drk([Ё  здддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁInne odliczeniaЁ 39.Podac rodzaj:                                                                     Ё40.                  Ё])
      mon_drk([Ё  Ё               Ё                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё               Ё            ]+padc(rozrzut(alltrim(P62o)),60)+[              Ё      ]+tran(P62,dRPIC)+[   Ё])
      mon_drk([Ё  Ё               Ё                                                                                      Ё                     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё F.   ODLICZENIE Z TYTULU WYDATKOW INWESTYCYJNYCH                                                                              Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Dodatkowa obnizka                                                                                   Ё41.                  Ё])
      mon_drk([Ё  Ё  -na podstawie rozporzadzenia Rady Ministrow z dnia 24.01.1995 (Dz.U.z 1995r. nr14,poz.63,z pozn.zm.)Ё                     Ё])
      mon_drk([Ё  Ё   zgodnie z art.5 ust.2 ustawy z dnia 21.11.1996r. (Dz.U.z 1996r. nr 137, poz.638, z pozn.zmianami)  Ё      ]+tran(P68,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё2.Wydatki inwestycyjne i premia inwestycyjna do odliczenia na podstawie art.26a ustawy w brzmieniu    Ё42.                  Ё])
      mon_drk([Ё  Ё  obowiaz.przed dniem 1.01.2001-w zwiazku z art.7ust.18-20 ustawy z dnia 9.11.2000(Dz.U.Nr104,poz.1104Ё      ]+tran(P67,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G.   DOCH&__O.D ZWOLNIONY OD PODATKU - na podstawie przepis&_o.w wykonawczych do ustawy z dn.20.10.94r. o specjalnych strefach       Ё])
      mon_drk([Ё      ekonomicznych (Dz.U.Nr123,Poz.600 z p&_o.&_x.niejszymi zmianami)                                                               Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁDoch&_o.d zwolniony od podatku                                                                           Ё43.                  Ё])
      mon_drk([Ё  ЁPozycji tej nie wypelniaja podatnicy korzystajacy ze zwolnien, o ktorych mowa w poz.31                Ё      ]+tran(P76,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё H.   DOCH&__O.D PO ODLICZENIACH                                                                                                   Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁDoch&_o.d po odliczeniu ulg i zwolnie&_n.                                                                   Ё44.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.33 nale&_z.y odj&_a.&_c. kwot&_e. z poz.od 34 do 43 (bez poz.37 i 39)                              Ё      ]+tran(P77,dRPIC)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё I. USTALENIE PODSTAWY OBLICZENIA PODATKU                                                                                      Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwoty zwiekszajace podstawe opodatkowania/zmniejszajace strate z tytulu utraty prawa do:              Ё45.                  Ё])
      mon_drk([Ё  Ё-zwolnienia-na podst.przep.wykon.do ustawy z dnia 20.10.1994 o SSE (Dz.U.Nr123,poz.600 z pozn.zm.)    Ё                     Ё])
      mon_drk([Ё  Ё-ulg inwest.-na podst.przep.rozp.RM z dn.25.01.1994 lub rozp.RM z dn.24.01.1995                       Ё      ]+tran(P75,dRPIC)+[   Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodstawa obliczenia podatku                                                                           Ё46.                  Ё])
      mon_drk([Ё  Ё(po zaokr&_a.gleniu do pe&_l.nych z&_l.otych)                                                                  Ё      ]+tran(P777,dRPIC)+[   Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё                                                                                                      Ё                     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё J. OBLICZENIE NALE&__Z.NEGO PODATKU                                                                                               Ё])
      mon_drk([цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё J.1. OBLICZENIE PODATKU                                                                                                       Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodatek od podstawy z poz.46 obliczony wed&_l.ug skali okre&_s.lonej w art.27 ustawy                        Ё47.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё      ]+tran(P79,dRPIC)+[   Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддды])
      mon_drk([3) Odliczenie nie dotyczy skladek, ktorych podstawe wymiaru stanowi dochod(przychod) wolny od podatku na podstawie art.21, 52])
      mon_drk([   i 52a ustawy oraz skladek, ktorych podstawe wymiaru stanowi dochod, od ktorego na podstawie przepisow ustawy z dnia 29.08.1997])
      mon_drk([   - Ordynacja podatkowa (Dz.U.z 1997r. Nr137, poz.926, z pozn.zm.) zaniechano poboru podatku])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([])
      mon_drk([PIT-5 (12) 2/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё J.2.ODLICZENIA OD PODATKU                                                                                                     Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Skladki na powszechne ubezpieczenie zdrowotne oplacone od poczatku roku bezposrednio przez podatnikaЁ48.                  Ё])
      mon_drk([Ё  Ё  zgodnie z przepisami o powszechnym ubezpieczeniu zdrowotnym, z zastrzezeniem art.27b ust.2 ustawy   Ё      ]+tran(p80,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё2.Ulgi inwestycyjne przyznane przed dniem 1 stycznia 1992 r. i nie wykorzystane w latach ubieg&_l.ych    Ё49.                  Ё])
      mon_drk([Ё  Ё                                                                                                      Ё      ]+tran(P81,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё3.Ulgi za wyszkolenie uczniow lub z tytulu zatrudnienia pracownikow w celu nauki zawodu przyznane     Ё50.                  Ё])
      mon_drk([Ё  Ё  na podstawie decyzji urzedu skarbowego                                                              Ё      ]+tran(P82,dRPIC)+[   Ё])
      mon_drk([Ё  цдддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  Ё4.Inne         Ё 51.Podac rodzaj:                                                                     Ё52.                  Ё])
      mon_drk([Ё  Ё  odliczenia   Ё                                                                                      Ё                     Ё])
      mon_drk([Ё  Ё  niewymienioneЁ            ]+padc(rozrzut(alltrim(P83o)),60)+[              Ё      ]+tran(P83,dRPIC)+[   Ё])
      mon_drk([Ё  Ё  w wier.1 do 3Ё                                                                                      Ё                     Ё])
      mon_drk([цддадддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё J.3.OBLICZENIE NALE&__Z.NEJ ZALICZKI                                                                                              Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁPodatek po odliczeniach od pocz&_a.tku roku                                                              Ё53.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.47 nale&_z.y odj&_a.&_c. kwot&_e. z poz.48-52 (bez 51). Je&_z.eli r&_o.&_z.nica jest liczb&_a. ujemn&_a., wpisa&_c. 0Ё      ]+tran(P85,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSuma nale&_z.nych zaliczek za poprzednie miesi&_a.ce. Nale&_z.y wpisa&_c. kwot&_e. z poz."Suma naleznych zaliczek od Ё54.                  Ё])
      mon_drk([Ё  Ёpoczatku roku" z pop.mie.Sk&_l.adaj&_a.c deklaracje po raz pierwszy w danym roku podatkowym nale&_z.y wpisa&_c. 0.Ё      ]+tran(P92,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNalezna zaliczka za miesiac                                                                           Ё55.                  Ё])
      mon_drk([Ё  ЁOd kwoty z poz.53 nale&_z.y odj&_a.&_c. kwot&_e. z poz.54. Je&_z.eli r&_o.&_z.nica jest liczb&_a. ujemn&_a., nale&_z.y wpisa&_c. 0     Ё      ]+tran(P93,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSuma nale&_z.nych zaliczek od pocz&_a.tku roku                                                              Ё56.                  Ё])
      mon_drk([Ё  ЁSuma kwot z poz.54 i 55                                                                               Ё      ]+tran(p94,dRPIC)+[   Ё])
      mon_drk([цддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё J.4.OGRANICZENIE POBORU ZALICZEK-na podstawie art.22 par.2a ustawy z dnia 29.08.1997r. Ordynacja Podatkowa (Dz.U.z 1997 nr137)Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё57.Numer(-y) decyzji organu podatkowego                      Ё58.Data(-y) decyzji organu podatkowego (dzien-miesiac-rok)    Ё])
      mon_drk([Ё  Ё                                                             Ё                                                              Ё])
      mon_drk([Ё  Ё          ]+padc(rozrzut(alltrim(P884)),40)+[           Ё          ]+p886+[                                  Ё])
      mon_drk([Ё  Ё                                                             Ё                                                              Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota wynikajaca z decyzji organu podatkowego                                                         Ё59.   ]+tran(p885,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota zrealizowana w poprzednich miesiacach                                                           Ё60.   ]+tran(p887,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota do zrealizowania w niniejszej deklaracji                                                        Ё61.                  Ё])
      mon_drk([Ё  ЁPodana kwota nie moze przekroczyc kwoty wykazanej w poz."Nalezna zaliczka za miesiac"                 Ё      ]+tran(p888,dRPIC)+[   Ё])
      mon_drk([цддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддд╢])
      mon_drk([Ё J.5.OBLICZENIE ZOBOWIAZANIA PRZYPADAJ&__A.CEGO DO ZAP&__L.ATY                                                                         Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддд╢])
      mon_drk([Ё  ЁZaliczka po ograniczeniu                                                                              Ё62.   ]+tran(P889,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNale&_z.ny zrycza&_l.towany podatek dochodowy od dochodu z remanentu likwidacyjnego                         Ё63.                  Ё])
      mon_drk([Ё  ЁKwota z poz.11 za&_l.&_a.cznika PIT-5/X wypelnia sie tylko w miesiacu likwidacji dzialalnosci gospodarczej  Ё      ]+tran(P88,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota do zap&_l.aty                                                                                      Ё64.                  Ё])
      mon_drk([Ё  ЁSuma kwot z pozycji 62 i 63                                                                           Ё      ]+tran(P89,dRPIC)+[   Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota odsetek naliczonych od dnia zaliczenia do kosztow uzyskania przychodow wydatkow na nabycie lub  Ё65.                  Ё])
      mon_drk([Ё  Ёwytworzenie we wlasnym zakresie skladnikow majatku do dnia zaliczenia ich do srodkow trwalych lub     Ё      ]+tran(P90,dRPIC)+[   Ё])
      mon_drk([Ё  Ёwartosci niematerialnych i prawnych-art.22e ust.1 pkt4 ustawy                                         Ё                     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╪])
      mon_drk([Ё K. POZAROLNICZA DZIA&__L.ALNO&__S.&__C. GOSPODARCZA (R&__O.WNIE&__Z. UDZIA&__L. W SP&__O.&__L.KACH NIE MAJ&__A.CYCH OSOBOWO&__S.CI PRAWNEJ ORAZ DZIALALNOSC MALZONKOW Ё])
      mon_drk([Ё  зддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Ё 66. Numer identyfikacyjny       ]+dzial_g[1,1]+[  Ё67. Identyfikator REGON             ]+dzial_g[1,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё68. Nazwa pe&_l.na                                                 Ё69. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[1,3],60)+[  Ё    ]+padc(dzial_g[1,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё70. Udzia&_l. w %          Ё71. Przych&_o.d            Ё72. Koszty              Ё73. Doch&_o.d              Ё74. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[1,5],3)+[     Ё     ]+tran(dzial_g[1,6],dRPICe)+[     Ё     ]+tran(dzial_g[1,7],dRPICe)+[     Ё       ]+tran(dzial_g[1,8],dRPIC)+[     Ё       ]+tran(dzial_g[1,9],dRPIC)+[     Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё2.Ё 75. Numer identyfikacyjny       ]+dzial_g[2,1]+[  Ё76. Identyfikator REGON             ]+dzial_g[2,2]+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё77..Nazwa pe&_l.na                                                 Ё78. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  Ё  ]+padc(dzial_g[2,3],60)+[  Ё    ]+padc(dzial_g[2,4],50)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 79. Udzia&_l. w %         Ё80. Przych&_o.d            Ё81. Koszty              Ё82. Doch&_o.d              Ё83. Strata              Ё])
      mon_drk([Ё  Ё                ]+str(dzial_g[2,5],3)+[     Ё     ]+tran(dzial_g[2,6],dRPICe)+[     Ё     ]+tran(dzial_g[2,7],dRPICe)+[     Ё       ]+tran(dzial_g[2,8],dRPIC)+[     Ё       ]+tran(dzial_g[2,9],dRPIC)+[     Ё])
      mon_drk([юддаддддддддддддддддддддддддаддддддддддддддддддддддддаддддддддддддддддддддддддаддддддддддддддддддддддддадддддддддддддддддддддддды])
      mon_drk([])
      mon_drk([                                                                                                                   PIT-5 (12) 3/4])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё L. POZAROLNICZA DZIA&__L.ALNO&__S.&__C. GOSPODARCZA PROWADZONA NA TERENIE SPECJALNEJ STREFY EKONOMICZNEJ                                  Ё])
      mon_drk([Ё  зддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Ё 84. Rodzaj dzialalnosci                                                                                                 Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё85. Numer Identyfikacji Podatkowej                              Ё86. Identyfikator REGON                                    Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё87. Nazwa pe&_l.na                                                 Ё88. Miejsce prowadzenia dzia&_l.alno&_s.ci                       Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддаддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё89. Numer zezwolenia                Ё 90.Data wydania zezwolenia             Ё 91. Data rozpoczecia dzialalnosci            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё92. Zasady prowadzenia dzialalnosci gospodarczej                                                                            Ё])
      mon_drk('Ё  Ё    [ ]1.podatnik nie korzysta ze zwolnien i prefer.  [ ]2.podatnik korzysta z preferencji  [ ]3.podatnik korzysta ze zwoln.Ё')
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё93. Udzia&_l. w %          Ё94. Przych&_o.d            Ё95. Koszty              Ё96. Doch&_o.d              Ё97. Strata              Ё])
      mon_drk([Ё  цддддддддддддддддддддддддаддддддддддддддддддддддддаддддддддддддддбдддддддддаддддддддддддддддддддддддадддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё98. Dochod zwolniony od podatku                                 Ё99. Kwota zwiekszajaca podstawe opodatkowania              Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё2.Ё 100.Rodzaj dzialalnosci                                                                                                 Ё])
      mon_drk([Ё  цддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё101.Numer Identyfikacji Podatkowej                              Ё102.Identyfikator REGON                                    Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё103.Nazwa pe&_l.na                                                 Ё104. Miejsce prowadzenia dzia&_l.alno&_s.ci                      Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддаддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё105.Numer zezwolenia                Ё106.Data wydania zezwolenia             Ё107. Data rozpoczecia dzialalnosci            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё108.Zasady prowadzenia dzialalnosci gospodarczej                                                                            Ё])
      mon_drk('Ё  Ё    [ ]1.podatnik nie korzysta ze zwolnien i prefer.  [ ]2.podatnik korzysta z preferencji  [ ]3.podatnik korzysta ze zwoln.Ё')
      mon_drk([Ё  цддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё109.Udzia&_l. w %          Ё110.Przych&_o.d            Ё111.Koszty              Ё112.Doch&_o.d              Ё113.Strata              Ё])
      mon_drk([Ё  цддддддддддддддддддддддддаддддддддддддддддддддддддаддддддддддддддбдддддддддаддддддддддддддддддддддддадддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё114.Dochod zwolniony od podatku                                 Ё115.Kwota zwiekszajaca podstawe opodatkowania              Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╪])
      mon_drk([Ё M. NAJEM, PODNAJEM, DZIER&__Z.AWA ORAZ INNE UMOWY O PODOBNYM CHARAKTERZE, A TAK&__Z.E WSP&__O.&__L.W&__L.ASNO&__S.&__C. I WSP&__O.LNE POSIADANIE              Ё])
      mon_drk([Ё  зддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Ё 116.&__X.r&_o.d&_l.o przychodu                                        Ё117.Miejsce po&_l.o&_z.enia &_x.r&_o.d&_l.a przychodu                     Ё])
      mon_drk([Ё  Ё  Ё                ]+padc(p120,40)+[     Ё    ]+padc(p121,50)+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё118. Udzia&_l. w %         Ё119.Przych&_o.d            Ё120.Koszty              Ё121.Doch&_o.d              Ё122.Strata              Ё])
      mon_drk([Ё  Ё                ]+str(p122,3)+[     Ё     ]+tran(p123,dRPICe)+[     Ё     ]+tran(p124,dRPICe)+[     Ё       ]+tran(p125,dRPIC)+[     Ё       ]+tran(p126,dRPIC)+[     Ё])
      mon_drk([Ё  цмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё  Ё2.Ё 123.&__X.r&_o.d&_l.o przychodu                                        Ё124.Miejsce po&_l.o&_z.enia &_x.r&_o.d&_l.a przychodu                     Ё])
      mon_drk([Ё  Ё  Ё                ]+padc(p127,40)+[     Ё    ]+padc(p128,50)+[     Ё])
      mon_drk([Ё  цддадддддддддддддддддддддбддддддддддддддддддддддддбддддддддддддддадддддддддбддддддддддддддддддддддддбдддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё125. Udzia&_l. w %         Ё126.Przych&_o.d            Ё127.Koszty              Ё128.Doch&_o.d              Ё129.Strata              Ё])
      mon_drk([Ё  Ё                ]+str(p129,3)+[     Ё     ]+tran(p130,dRPICe)+[     Ё     ]+tran(p131,dRPICe)+[     Ё       ]+tran(p132,dRPIC)+[     Ё       ]+tran(p133,dRPIC)+[     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╪])
      mon_drk([Ё N. INFORMACJA O ZA&__L.&__A.CZNIKACH                                                                                                  Ё])
      mon_drk([Ё    W ka&_z.dej z poni&_z.szych rubryk nale&_z.y poda&_c. liczb&_e. do&_l.&_a.czonych formularzy o podanym symbolu (remanent&_o.w)                     Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё130.PIT-5/A                       Ё131.PIT-5/X                      Ё132.Remanent likwidacyjny                              Ё])
      mon_drk([Ё  Ё                                  Ё                                 Ё                                                       Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё O. O&__S.WIADCZENIE I PODPIS PODATNIKA                                                                                            Ё])
      mon_drk([Ё    O&_s.wiadczam, &_z.e przepisy ustawy karnej skarbowej o odpowiedzialno&_s.ci za podanie danych niezgodnych z rzeczywisto&_s.ci&_a. s&_a. mi  Ё])
      mon_drk([Ё    znane.                                                                                                                     Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё133.Data wype&_l.nienia deklaracji (dzie&_n. - miesi&_a.c - rok)  Ё134.Podpis podatnika                                              Ё])
      mon_drk([Ё  Ё                                                         Ё                                                                  Ё])
      mon_drk([Ё  Ё                                                         Ё                                                                  Ё])
      mon_drk([ц*******************************************************************************************************************************╢])
      mon_drk([Ё P. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё135.Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё136.Identyfikator urz&_e.dnika przyjmuj&_a.cego formularz           Ё137.Podpis urz&_e.dnika przyjmuj&_a.cego formularz                 Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([POUCZENIE])
      mon_drk([W przypadku niewplacenia w obowiazujacym terminie kwot z poz.62 i 63 lub wplacenie ich w niepelnej wysokosci,                    ])
      mon_drk([niniejsza deklaracja stanowi podstawe do wystawienia tytulu wykonawczego, zgodnie z art.26a ustawy z dnia 17 czerwca 1966r.      ])
      mon_drk([o postepowaniu egzekucyjnym w administracji (Dz.U.z 1991r. Nr 36, poz.161 z pozn.zm.).                                           ])
      mon_drk([PIT-5 (12) 4/4])
      mon_drk([Ч])
end
