/************************************************************************

AMi-BOOK

Copyright (C) 1991-2014  AMi-SYS s.c.
              2015-2020  GM Systems Micha┬ Gawrycki (gmsystems.pl)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

private _grupa1,_grupa2,_grupa3,_grupa4,_grupa5,_grupa,_koniec,_szerokosc,_numer,_lewa,_prawa,_strona,_czy_mon,_czy_close
private _t1,_t2,_t3,_t4,_t5,_t6,_t7,_t8,_t9,_t10,_t11,_t12,_t13,_t14,_t15
begin sequence
      @ 1,47 say space(10)
      *-----parametry wewnetrzne-----
      _papsz=1
      _lewa=1
      _prawa=129
      _strona=.n.
      _czy_mon=.t.
      _czy_close=.t.
      czesc=1
      *------------------------------
      _szerokosc=129
      *@@@@@@@@@@@@@@@@@@@@ OTWARCIE BAZ DANYCH @@@@@@@@@@@@@@@@@@@@@@
      mon_drk([Ж]+procname())
      mon_drk([здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддбддддддддддддддддддд©])
      mon_drk([Ё1.Identyfikator podatkowy NIP podatnika                              Ё2.Nr dokumentu                       Ё3.Status           Ё])
      mon_drk([Ё                                        ]+rozrzut(P4)+[   Ё                                     Ё                   Ё])
      mon_drk([юдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддддддддддддаддддддддддддддддддды])
      mon_drk([V A T - 7]+zPOLESTO+[            DEKLARACJA DLA PODATKU OD TOWAR&__O.W I US&__L.UG])
      mon_drk([                          зддддддддддддддбдддддддддддддддддд©])
      mon_drk([                          Ё4.]+zPOLE4+[     Ё5.Rok             Ё])
      mon_drk([                     ZA   Ё     ]+rozrzut(p5a)+[     Ё       ]+rozrzut(p5b)+[   Ё])
      mon_drk([                          юддддддддддддддадддддддддддддддддды])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      do case
      case zVATFORDR='7K'
         mon_drk([ЁPodstawa prawna:Art.99 ust2lub3 ustawy z dn.11.03.2004o podat.od towarow i uslug(Dz.U.z2011rNr177,poz.1054)zwanej dalej "ustawaЁ])
         mon_drk([ЁSkladajacy     :Mali podatnicy,o ktorych mowa w art.2 pkt 25 ustawy,obowiazani do skladania deklaracji za okresy kwartalne,    Ё])
         mon_drk([Ё                zgodnie z art.99 ust.2 lub 3 ustawy.                                                                           Ё])
      case zVATFORDR='7 '
         mon_drk([ЁPodstawa prawna:Art.99 ust.1 ustawy z dn.11.03.2004 o podatku od towarow i uslug (Dz.U.z2011r.Nr177,poz.1054,z pozn.zm.) zwanejЁ])
         mon_drk([Ё                dalej "ustawa".                                                                                                Ё])
         mon_drk([ЁSkladajacy     :Podatnicy,o ktorych mowa w art.15 ustawy,obowiazani do sklad.deklar.za okresy mies.zgodnie z art.99ust.1 ustawyЁ])
      case zVATFORDR='7D'
         mon_drk([ЁPodstawa prawna:Art.99 ust.3 ustawy z dn.11.03.2004 o podatku od towarow i uslug(Dz.U.z2011rNr177,poz.1054)zwanej dalej "ustawaЁ])
         mon_drk([ЁSkladajacy     :Podatnicy,o ktorych mowa w art.15 ustawy,inni niz mali,obowiazani do skladania deklaracji za okresy kwartal-   Ё])
         mon_drk([Ё                ne, zgodnie z art.99 ust.3 ustawy.                                                                             Ё])
      endcase
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё A. MIEJSCE I CEL SK&__L.ADANIA DEKLARACJI                                                                                         Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё6.Urz&_a.d skarbowy, do kt&_o.rego adresowana jest deklaracja          Ё7.Cel zlozenia formularza                                 Ё])
      mon_drk([Ё  Ё   ]+padc(alltrim(P6),60)+[  Ё  ]+iif(kordek='D','[XX]','[  ]')+[ 1.zlozenie deklaracji   ]+iif(kordek='K','[XX]','[  ]')+[ 2.korekta deklaracji  Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё B. DANE IDENTYFIKACYJNE PODATNIKA                                                                                             Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё8.Rodzaj podatnika (zaznaczy&_c. w&_l.a&_s.ciwy kwadrat)                                                                             Ё])
      mon_drk([Ё  Ё                         ]+iif(spolka_,'[XX]','[  ]')+[  1.Podatnik nieb&_e.d&_a.cy osob&_a. fizyczn&_a.            ]+iif(.not.spolka_,'[XX]','[  ]')+[  2.Osoba fizyczna                        Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё9.]+iif(spolka_,'Nazwa pe&_l.na, REGON'+space(22),'Nazwisko, pierwsze imie, data urodzenia ')+[                                                                                  Ё])
      mon_drk([Ё  Ё ]+padc(rozrzut(alltrim(P8))+[     ]+P11,120)+[   Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё C. ROZLICZENIE PODATKU NALEZNEGO                                    ЁPodstawa opodatkowania w zl Ё    Podatek nale&_z.ny w z&_l.    Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 1.Dost.tow.oraz swiad.uslug,na terytorium kraju,zwolnione od VAT Ё10.      ]+kwota(P64,14,0)+[     Ё............................Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 2.Dostawa towarow oraz swiadczenie uslug, poza terytorium kraju  Ё11.      ]+kwota(P64exp,14,0)+[     Ё............................Ё])
      mon_drk([Ё  юдддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё      Ё 2a. w tym swiadczenie uslug,o ktorych mowa art.100ust.1 pkt 4Ё12.      ]+kwota(P64expue,14,0)+[     Ё............................Ё])
      mon_drk([Ё  здддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 3.Dostawa towarow oraz swiadczenie uslug, na terytorium kraju,   Ё13.                         Ё............................Ё])
      mon_drk([Ё  Ё   opodatkowana stawka 0%                                         Ё         ]+kwota(P67,14,0)+[     Ё............................Ё])
      mon_drk([Ё  юдддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё      Ё 3a. w tym dostawa towarow, o ktorej mowa w art.129 ustawy    Ё14.      ]+kwota(P67art129,14,0)+[     Ё............................Ё])
      mon_drk([Ё  здддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 4.Dostawa towarow oraz swiadczenie uslug, na terytorium kraju,   Ё15.                         Ё16.                         Ё])
      mon_drk([Ё  Ё   opodatkowana stawka odpowiednio 3% albo 5%                     Ё         ]+kwota(P61+P61a,14,0)+[     Ё         ]+kwota(P62+P62a,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 5.Dostawa towarow oraz swiadczenie uslug, na terytorium kraju,   Ё17.                         Ё18.                         Ё])
      mon_drk([Ё  Ё   opodatkowana stawka odpowiednio 7% albo 8%                     Ё         ]+kwota(P69,14,0)+[     Ё         ]+kwota(P70,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 6.Dostawa towarow oraz swiadczenie uslug, na terytorium kraju,   Ё19.                         Ё20.                         Ё])
      mon_drk([Ё  Ё   opodatkowana stawka odpowiednio 22% albo 23%                   Ё         ]+kwota(P71,14,0)+[     Ё         ]+kwota(P72,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 7.Wewnatrzwspolnotowa dostawa towarow                            Ё21.      ]+kwota(P65ue,14,0)+[     Ё............................Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 8.Eksport towarow                                                Ё22.      ]+kwota(P65,14,0)+[     Ё............................Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 9.Wewnatrzwspolnotowe nabycie towarow                            Ё23.      ]+kwota(P65dekue,14,0)+[     Ё24.      ]+kwota(P65vdekue,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё10.Import towarow,podlegajacy rozliczeniu zgodnie z art.33a ustawyЁ25.      ]+kwota(P65dekit,14,0)+[     Ё26.      ]+kwota(P65vdekit,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё11.Import us┬ug z wy┬. us┬ug do kt╒rych stos.si╘ art.28b ustawy   Ё27.      ]+kwota(p65dekus,14,0)+[     Ё28.      ]+kwota(p65vdekus,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё12.Import us┬ug do kt╒rych stosuje si╘ art.28b ustawy             Ё29.      ]+kwota(P65dekusu,14,0)+[     Ё30.      ]+kwota(P65vdekusu,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё13.Dost.tow.dla ktorej podat.jest nabywca art.17 ust.1 pkt 1 lub 8Ё31.      ]+kwota(SEK_CV7net,14,0)+[     Ё                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё14.Dost.tow.dla ktorej podat.jest nabywca art.17 ust.1 pkt 5      Ё32.      ]+kwota(0,14,0)+[     Ё33.      ]+kwota(0,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё15.Dost.tow.dla ktorej podat.jest nabywca art.17 ust.1 pkt 1 lub 8Ё34.      ]+kwota(P65dekwe,14,0)+[     Ё35.      ]+kwota(P65vdekwe,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё16.Kwota pod.nalez.od towarow i uslug objetych spisem z natury,o ktorym mowa w art.14 ust.5ustaЁ36.      ]+kwota(Pp12,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё17.Zwrot odl.lub zwr╒conej kwoty wydatk. na zakup kas rejestr.,o ktorym mowa w art.111ust.6ustaЁ37.      ] + kwota( art111u6, 14, 0 ) + [     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё18.Kwota podatku naleznego od wewnatrzwspolnotowego nabycia srodkow transportu, wykazanego     Ё38.                         Ё])
      mon_drk([Ё  Ё   w poz.34,podlegajaca wplacie w terminie,o ktorym mowa w art.103 ust.3 ustawy,w zwiazku ust.4Ё         ]+kwota(znowytran,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё19.Kwota podatku od wewnatrzwspolnotowego nabycia paliw silnikowych, podlegaj╔ca wp┬acie w     Ё39.      ]+kwota(zKOL39,14,0)+[     Ё])
      mon_drk([Ё  Ё   terminach o kt╒rych mowa w art. 103 ust. 5a i 5b ustawy.                                    Ё                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддиммммммммммммммммммммммммммммкмммммммммммммммммммммммммммм╩])
      mon_drk([Ё  ЁRAZEM                                                             ╨40.      ]+kwota(P75,14,0)+[     ╨41.      ]+kwota(P76,14,0)+[     ╨])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё D. ROZLICZENIE PODATKU NALICZONEGO                                                                                            Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё D.1. PRZENIESIENIA                                                                               Ё Podatek do odliczenia w z&_l..Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota nadwyzki z poprzedniej deklaracji                                                        Ё42.      ]+kwota(Pp8,14,0)+[     Ё])
      mon_drk([юддадддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддды])
      mon_drk([                                                                                                                   VAT-7]+zPOLESTO+zWERVAT+[ 1/2])
      mon_drk([зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©])
      mon_drk([Ё D.2. NABYCIE TOWAROW I USLUG ORAZ PODATEK NALICZONY Z UWZGL.KOREKT  Ё     Wartosc netto w zl.    Ё   Podatek naliczony w z&_l..  Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё1.Nabycie towarow i uslug zaliczanych u podatnika do srodkow trwa.Ё43.      ]+kwota(P45dek,14,0)+[     Ё44.      ]+kwota(P46dek,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё2.Nabycie towarow i uslug pozostalych                             Ё45.      ]+kwota(P49dek,14,0)+[     Ё46.      ]+kwota(P50dek,14,0)+[     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё D.3. PODATEK NALICZONY - DO ODLICZENIA (w z&_l.)                                                                                 Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKorekta podatku naliczonego od nabycia srodkow trwalych                                        Ё47.      ]+kwota(zkorekst,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKorekta podatku naliczonego od pozostalych nabyc                                               Ё48.      ]+kwota(zkorekpoz,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKorekta podatku naliczonego, o kt╒rej mowa w art. 89b ust. 1 ustawy                            Ё49.      ]+kwota(art89b1,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKorekta podatku naliczonego, o kt╒rej mowa w art. 89b ust. 4 ustawy                            Ё50.      ]+kwota(art89b4,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддимммммммммммммммммммммммммммм╩])
      mon_drk([Ё  ЁKwota podatku naliczonego do odliczenia. Suma kwot z poz.42,44,46,47,48 i 50                   ╨51.      ]+kwota(P79,14,0)+[     ╨])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё E. OBLICZENIE WYSOKO&__S.CI ZOBOWI&__A.ZANIA PODATKOWEGO LUB KWOTY ZWROTU (w z&_l.)                                                      Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota wydatkowana na zakup kas rejestrujacych, do odliczenia w danym okresie rozliczeniowym    Ё52.      ]+kwota(P98a,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota podatku obj&_e.ta zaniechaniem poboru                                                       Ё53.      ]+kwota(pp13,14,0)+[     Ё])

      if zVATFORDR='7 ' .or. zVATFORDR='7K'

      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддимммммммммммммммммммммммммммм╩])
      mon_drk([Ё  ЁKwota podatku podlegaj&_a.ca wp&_l.acie do urz&_e.du skarbowego ***)                                    ╨ 54.                        ╨])
      mon_drk([Ё  Ё                                                                                               ╨         ]+kwota(P98b,14,0)+[     ╨])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддхмммммммммммммммммммммммммммм╪])
      mon_drk([Ё  ЁKwota wydatkowana na zakup kas rejestruj&_a.cych, przys&_l.uguj&_a.ca do zwrotu w danym okresie rozlicz.Ё55.      ]+kwota(P99a,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNadwy&_z.ka podatku naliczonego nad nale&_z.nym.                                                     Ё56.      ]+kwota(P99,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддимммммммммммммммммммммммммммм╩])
      mon_drk([Ё  Ё          ЁKwota do zwrotu na rachunek bankowy wskazany przez podatnika                        ╨57.      ]+kwota(P99c,14,0)+[     ╨])
      mon_drk([Ё  Ё          юдддбддддддддддддддддддддддбддддддддддддддддддддддддддддбддддддддддддддддддддддддддддхмммммммммммммммммммммммммммм╪])
      mon_drk([Ё  Ё              Ё                      Ё58. w terminie 25 dni       Ё59. w terminie 60 dni       Ё60. w terminie 180 dni      Ё])
      mon_drk([Ё  Ё              Ё w tym kwota do zwrotuЁ         ]+kwota(P99abc,14,0)+[     Ё         ]+kwota(P99ab,14,0)+[     Ё         ]+kwota(P99b,14,0)+[     Ё])
      mon_drk([Ё  Ё          здддаддддддддддддддддддддддаддддддддддддддддддддддддддддаддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё          ЁKwota do przeniesienia na nastepny okres rozliczeniowy                              Ё61.      ]+kwota(P99d,14,0)+[     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё F. INFORMACJE DODATKOWE                                                                                                       Ё])
      mon_drk([Ё    Podatnik wykonywal w okresie rozliczeniowym czynnosci, o ktorych mowa (zaznaczyc wlasciwy kwadrat):                        Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 62.                          Ё 63.                          Ё 64.                          Ё 65.                           Ё])
      mon_drk([Ё  Ё      ]+iif(zf2='T','[XX]','[  ]')+[ art.119 ustawy ]+[    Ё   ]+iif(zf3='T','[XX]','[  ]')+[ art.120ust.4lub5ust]+[   Ё     ]+iif(zf4='T','[XX]','[  ]')+[ art.122 ustawy ]+[     Ё      ]+iif(zf5='T','[XX]','[  ]')+[ art.136 ustawy      Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G. INFORMACJA O ZALACZNIKACH  Do niniejszej deklaracji dolaczono (zaznaczyc wlasciwy kwadrat)                                 Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 66.Wniosek o zwrot podatku                              Ё 67.Wniosek o przyspieszenie terminu zwrotu podatku               Ё])
      mon_drk('Ё  Ё                        [  ] 1.tak       [  ] 2. nie     Ё       [  ] 1.tak                         [  ] 2.nie              Ё')
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 68.Zawiadomienie o skorygowaniu podstawy opodatkowania                 Ё 69.Jezeli w poz.68 zaznaczono kwadrat nr1,        Ё])
      mon_drk('Ё  Ё    oraz kwoty podatku naleznego (VAT-ZD)      [  ] 1.tak   [  ] 2. nie Ё    nalezy podac ilosc zalacznikow VAT-ZD          Ё')
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё H. O&__S.WIADCZENIE PODATNIKA LUB OSOBY REPREZENTUJ&__A.CEJ PODATNIKA                                                                 Ё])
      mon_drk([ЁO&_s.wiadczam, &_z.e przepisy ustawy karnej skarbowej o odpowiedzialno&_s.ci za podanie danych niezgodnych z rzeczywistosci&_a. s&_a. mi znaneЁ])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 70.Imie     ]+zDEKLIMIE+[       Ё 71.Nazwisko      ]+zDEKLNAZWI+[   Ё 72.Podpis (i pieczatka) podatnika lub osoby  Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддд╢    reprezentujacej podatnika                 Ё])
      mon_drk([Ё  Ё 73.Telefon kontaktowy             Ё 74.Data wypelnienia (dzien-miesiac-rok) Ё                                              Ё])
      mon_drk([Ё  Ё     ]+zDEKLTEL+[     Ё                                         Ё                                              Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё I. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 75.Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  Ё                                                                                                                            Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 76.Identyfikator przyjmuj&_a.cego formularz                     Ё 77.Podpis przyjmuj&_a.cego formularz                           Ё])
      mon_drk([Ё  Ё                                                              Ё                                                             Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([1) Zgodnie z art. 81 ustawy z dnia 29 sierpnia 1997 r. ? Ordynacja podatkowa (Dz. U. z 2015 r. poz. 613, z p╒╚n. zm.).           ])
      mon_drk([                                                         ***) POUCZENIE                                                          ])
      mon_drk([W przypadku niewp┬acenia w obowi╔zuj╔cym terminie kwoty z poz.54 lub wp┬acenia jej w niepe┬nej wysoko≤ci, niniejsza deklaracja   ])
      mon_drk([stanowi podstaw╘ do wystawienia tytu┬u wykonawczego zgodnie z przepisami ustawy z dnia 17 czerwca 1966 r. o post╘powaniu         ])
      mon_drk([egzekucyjnym w administracji (Dz. U. z 2014 r. poz. 1619, z p╒╚n. zm.). Za podanie nieprawdy lub zatajenie prawdy i przez to     ])
      mon_drk([nara╬enie podatku na uszczuplenie grozi odpowiedzialno≤├ przewidziana w Kodeksie karnym skarbowym                                ])
      mon_drk([VAT-7]+zPOLESTO+zWERVAT+[ 2/2])

      else
	
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNalezne zobowiazanie podatkowe podlegajace wplacie do urzedu skarbowego                        Ё54.      ]+kwota(P98b,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁSuma zaliczek na podatek wplaconych w kwartale, ktorego deklaracja dotyczy                     Ё55.      ]+kwota(zVATZALMIE,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota nadplaty                                                                                 Ё56.      ]+kwota(zVATNADKWA,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддимммммммммммммммммммммммммммм╩])
      mon_drk([Ё  ЁDO ZAPLATY                                                                                     ╨57.      ]+kwota(P98dozap,14,0)+[     ╨])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддлмммммммммммммммммммммммммммм╧])
      mon_drk([Ё  ЁNADPLATA                                                                                       ╨58.      ]+kwota(P98rozn,14,0)+[     ╨╨])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддхмммммммммммммммммммммммммммм╪])
      mon_drk([Ё  ЁZaliczenie nadplaty na poczet przyszlych zobowiazan podatkowych     Ё59.]+iif(p98taknie='T','[XX] 1.tak  [  ] 2.nie','[  ] 1.tak  [XX] 2.nie')+[ Ё60.      ]+kwota(P98doprze,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁKwota wydatkowana na zakup kas rejestruj&_a.cych, przys&_l.uguj&_a.ca do zwrotu w danym okresie rozlicz.Ё61.      ]+kwota(P99a,14,0)+[     Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  ЁNadwy&_z.ka podatku naliczonego nad nale&_z.nym.                                                     Ё62.      ]+kwota(P99,14,0)+[     Ё])
      mon_drk([Ё  цддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддимммммммммммммммммммммммммммм╩])
      mon_drk([Ё  Ё          ЁKwota do zwrotu na rachunek bankowy wskazany przez podatnika                        ╨63.      ]+kwota(P99c,14,0)+[     ╨])
      mon_drk([Ё  Ё          юдддбддддддддддддддддддддддбддддддддддддддддддддддддддддбддддддддддддддддддддддддддддхмммммммммммммммммммммммммммм╪])
      mon_drk([Ё  Ё              Ё                      Ё64. w terminie 25 dni       Ё65. w terminie 60 dni       Ё66. w terminie 180 dni      Ё])
      mon_drk([Ё  Ё              Ё w tym kwota do zwrotuЁ         ]+kwota(P99abc,14,0)+[     Ё         ]+kwota(P99ab,14,0)+[     Ё         ]+kwota(P99b,14,0)+[     Ё])
      mon_drk([Ё  Ё          здддаддддддддддддддддддддддаддддддддддддддддддддддддддддаддддддддддддддддддддддддддддедддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё          ЁKwota do przeniesienia na nastepny okres rozliczeniowy                              Ё67.      ]+kwota(P99d,14,0)+[     Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё F. INFORMACJE DODATKOWE   Podatnik wykonywal w okresie rozliczeniowym czynnosci, o ktorych mowa (zaznaczyc wlasciwy kwadrat): Ё])
      mon_drk([Ё  зддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 68.  ]+iif(zf2='T','[XX]','[  ]')+[ art.119 ustawy ]+[  Ё 69. ]+iif(zf3='T','[XX]','[  ]')+[ art.120ust.4lub5ust]+[   Ё 70. ]+iif(zf4='T','[XX]','[  ]')+[ art.122 ustawy ]+[     Ё 71.  ]+iif(zf5='T','[XX]','[  ]')+[ art.136 ustawy      Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё G. INFORMACJA O ZALACZNIKACH    Do niniejszej deklaracji dolaczono (zaznaczyc wlasciwy kwadrat)                               Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 72.Wniosek o zwrot podatku          Ё 73.Wniosek o przyspieszenie        Ё 74.Wniosek o zaliczenie nadplaty na poczet      Ё])
      mon_drk([Ё  Ё                                     Ё    terminu zwrotu podatku          Ё    przyszlych zobowiazan podatkowych            Ё])
      mon_drk('Ё  Ё      [  ] 1.tak       [  ] 2. nie   Ё      [  ] 1.tak       [  ] 2.nie   Ё            [  ] 1.tak       [  ] 2.nie          Ё')
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддддадддддддддддддддддддддддддддбддддддддаддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 75.Zawiadomienie o skorygowaniu podstawy opodatkowania oraz     Ё 76.Jezeli w poz.70 zaznaczono kwadrat nr1, nalezy podac  Ё])
      mon_drk('Ё  Ё    kwoty podatku naleznego (VAT-ZD)   [  ] 1.tak   [  ] 2.nie   Ё    ilosc zalacznikow VAT-ZD                              Ё')
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё H. O&__S.WIADCZENIE PODATNIKA LUB OSOBY REPREZENTUJ&__A.CEJ PODATNIKA                                                                 Ё])
      mon_drk([ЁO&_s.wiadczam, &_z.e przepisy ustawy karnej skarbowej o odpowiedzialno&_s.ci za podanie danych niezgodnych z rzeczywistosci&_a. s&_a. mi znaneЁ])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддбдддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 77.Imie       ]+zDEKLIMIE+[     Ё 78.Nazwisko    ]+zDEKLNAZWI+[     Ё 79.Podpis (i pieczatka) podatnika lub osoby  Ё])
      mon_drk([Ё  цдддддддддддддддддддддддддддддддддддеддддддддддддддддддддддддддддддддддддддддд╢    reprezentujacej podatnika                 Ё])
      mon_drk([Ё  Ё 80.Telefon kontaktowy             Ё 81.Data wypelnienia (dzien-miesiac-rok) Ё                                              Ё])
      mon_drk([Ё  Ё     ]+zDEKLTEL+[     Ё                                         Ё                                              Ё])
      mon_drk([цммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╢])
      mon_drk([Ё I. ADNOTACJE URZ&__E.DU SKARBOWEGO                                                                                                Ё])
      mon_drk([Ё  здддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 82.Uwagi urz&_e.du skarbowego                                                                                                 Ё])
      mon_drk([Ё  цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддбддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢])
      mon_drk([Ё  Ё 83.Identyfikator przyjmuj&_a.cego formularz                     Ё 84.Podpis przyjmuj&_a.cego formularz                           Ё])
      mon_drk([юддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддаддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды])
      mon_drk([                                                         ***) POUCZENIE                                                          ])
      mon_drk([W przypadku niewp┬acenia w obowi╔zuj╔cym terminie kwoty z poz.57 lub wp┬acenia jej w niepe┬nej wysoko≤ci, niniejsza deklaracja   ])
      mon_drk([stanowi podstaw╘ do wystawienia tytu┬u wykonawczego zgodnie z przepisami ustawy z dnia 17 czerwca 1966 r. o post╘powaniu         ])
      mon_drk([egzekucyjnym w administracji (Dz. U. z 2016 r. poz. 599, z p╒╚n. zm.). Za podanie nieprawdy lub zatajenie prawdy i przez to      ])
      mon_drk([nara╬enie podatku na uszczuplenie grozi odpowiedzialno≤├ przewidziana w Kodeksie karnym skarbowym                                ])
      mon_drk([VAT-7]+zPOLESTO+zWERVAT+[ 2/2])
      endif
      mon_drk([Ч])
end
